
def obtain_tipo_tributo(valor):
    tributos = [{'codigo': 86, 'tipo': 'COSIRF'}, {'codigo': 1038, 'tipo': 'COSIRF'}, {'codigo': 5602, 'tipo': 'PisPasep'},
     {'codigo': 5629, 'tipo': 'COFINS'}, {'codigo': 7811, 'tipo': 'COSIRF'}, {'codigo': 561, 'tipo': 'IRRF'},
     {'codigo': 1410, 'tipo': 'INSS'}, {'codigo': 1587, 'tipo': 'COSIRF'},
     {'codigo': 2185, 'tipo': 'ContribuicaoPrevidenciaria'}, {'codigo': 3562, 'tipo': 'IRRF'},
     {'codigo': 588, 'tipo': 'IRRF'}, {'codigo': 3373, 'tipo': 'IRPJ'}, {'codigo': 6012, 'tipo': 'CSLL'},
     {'codigo': 422, 'tipo': 'IRRF'}, {'codigo': 5434, 'tipo': 'PisPasep'}, {'codigo': 5442, 'tipo': 'COFINS'},
     {'codigo': 8741, 'tipo': 'CIDE'}, {'codigo': 5706, 'tipo': 'IRRF'}, {'codigo': 5952, 'tipo': 'CSRF'},
     {'codigo': 5856, 'tipo': 'COFINS'}, {'codigo': 2484, 'tipo': 'CSLL'}, {'codigo': 5993, 'tipo': 'IRPJ'},
     {'codigo': 481, 'tipo': 'IRRF'}, {'codigo': 473, 'tipo': 'IRRF'}, {'codigo': 1708, 'tipo': 'IRRF'},
     {'codigo': 8045, 'tipo': 'IRRF'}, {'codigo': 6912, 'tipo': 'PisPasep'}, {'codigo': 2362, 'tipo': 'IRPJ'},
     {'codigo': 5123, 'tipo': 'IPI'}, {'codigo': 3280, 'tipo': 'IRRF'}, {'codigo': 9385, 'tipo': 'IRRF'},
     {'codigo': 4444, 'tipo': 'IRRF'}, {'codigo': 289, 'tipo': 'ContribuicaoPrevidenciaria'},
     {'codigo': 1150, 'tipo': 'IOF'}, {'codigo': 5529, 'tipo': 'CPMF'}, {'codigo': 2864, 'tipo': 'Simples'},
     {'codigo': 3208, 'tipo': 'IRRF'}, {'codigo': 8047, 'tipo': 'Depósito Judicial - Outros'},
     {'codigo': 9412, 'tipo': 'IRRF'}, {'codigo': 2172, 'tipo': 'COFINS'}, {'codigo': 8109, 'tipo': 'PIS/PASEP'},
     {'codigo': 2089, 'tipo': 'IRPJ'}, {'codigo': 2372, 'tipo': 'CSLL'}, {'codigo': 9453, 'tipo': 'IRRF'},
     {'codigo': 2063, 'tipo': 'IRRF - Tributação Exclusiva sobre Remuneração Indireta'},
     {'codigo': 916, 'tipo': 'IRRF'}, {'codigo': 3008, 'tipo': 'Royalties Até 5%\xa0'},
     {'codigo': 5936, 'tipo': 'IRRF'}, {'codigo': 6621, 'tipo': 'INSS'}, {'codigo': 5960, 'tipo': 'CSRF'},
     {'codigo': 5979, 'tipo': 'CSRF'}, {'codigo': 5982, 'tipo': 'Recuperação Judicial'},
     {'codigo': 5149, 'tipo': 'IRRF'}, {'codigo': 13, 'tipo': 'TAXA FISCALIZAÇÃO CVM'},
     {'codigo': 19, 'tipo': 'TRANSFERENCIAS CORRENTES DOS MUNICÍPIOS'},
     {'codigo': 94, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - BAGAGEM ACOMPANHADA'},
     {'codigo': 107, 'tipo': 'IE - IMPOSTO EXPORTAÇÃO - OUTROS'}, {'codigo': 190, 'tipo': 'IRPF - CARNÊ LEÃO'},
     {'codigo': 211, 'tipo': 'IRPF - DECLARAÇÃO DE AJUSTE ANUAL, DECLARAÇÃO DE SAÍDA DEFINITIVA'},
     {'codigo': 220, 'tipo': 'IRPJ-PJ OBRIGADAS AO LUCRO REAL – ENTIDADES NÃO FINANCEIRAS – BALANÇO TRIMESTRAL'},
     {'codigo': 246, 'tipo': 'IRPF - COMPLEMENTAÇÃO MENSAL'},
     {'codigo': 457, 'tipo': 'RECEITA DIVIDA ATIVA - CONTRIBUIÇÃO AÇÚCAR E ÁLCOOL'},
     {'codigo': 490, 'tipo': 'IRRF - APLICAÇÕES EM FUNDOS DE INVESTIMENTO DE CONVERSÃO DE DÉBITOS EXTERNOS'},
     {'codigo': 668, 'tipo': 'IPI - BEBIDAS'}, {'codigo': 676, 'tipo': 'IPI - AUTOMÓVEIS'},
     {'codigo': 692, 'tipo': 'DIVERSAS RECEITAS'}, {'codigo': 810, 'tipo': 'RECEITA DÍVIDA ATIVA - PIS'},
     {'codigo': 836, 'tipo': 'RECEITA DÍVIDA ATIVA - PASEP'},
     {'codigo': 924, 'tipo': 'IRRF - DEMAIS RENDIMENTOS CAPITAL'},
     {'codigo': 936, 'tipo': 'REMUNERAÇÃO DISPONIBILIDADE TESOURO - OUTROS'},
     {'codigo': 1009, 'tipo': 'TAXA DE FISCALIZAÇÃO MERCADOS SEGURO, CAPITALIZAÇÃO E PREVIDÊNCIA PRIVADA'},
     {'codigo': 1020, 'tipo': 'IPI - CIGARROS CONTENDO TABACO'},
     {'codigo': 8508, 'tipo': 'REMUNERAÇÃO EXCESSO SOLICITADO CEF DEVOLUÇÃO DEPOSITO CONTRIBUINTE'},
     {'codigo': 1054, 'tipo': 'IRPF - DEVOLUÇÃO RESTITUIÇÃO INDEVIDA -TRIBUTÁRIO'},
     {'codigo': 1070, 'tipo': 'ITR - EXERCÍCIO 1997 E POSTERIORES'},
     {'codigo': 1089, 'tipo': 'IE - IMPOSTO EXPORTAÇÃO - CACAU'},
     {'codigo': 1097, 'tipo': 'IPI - MÁQUINAS, APARELHOS E MATERIAL DE TRANSPORTE'},
     {'codigo': 1134, 'tipo': 'RECEITA DÍVIDA ATIVA - FINSOCIAL'},
     {'codigo': 1142, 'tipo': 'RECEITA DÍVIDA ATIVA - IOF'},
     {'codigo': 1187, 'tipo': 'CONTRIBUIÇÃO SOBRE RECEITA CONCURSO PROGNÓSTICOS'},
     {'codigo': 1281, 'tipo': 'TRANSFERENCIAS DE INSTITUIÇÕES PRIVADAS - FNS'},
     {'codigo': 1290, 'tipo': 'RESTITUIÇÕES - FNS'}, {'codigo': 1345, 'tipo': 'MULTA ATRASO ENTREGA DCTF'},
     {'codigo': 1364, 'tipo': 'ALIENAÇÃO DE BENS IMÓVEIS - LEI 8.011/1990 E LEI 8.025/1990 - SPU'},
     {'codigo': 1404, 'tipo': 'COMPENSAÇÕES FINANCEIRAS - RECURSOS HÍDRICOS - ANEEL'},
     {'codigo': 1420, 'tipo': 'COMPENSAÇÕES FINANCEIRAS - RECURSOS MINERAIS - DNPM'},
     {'codigo': 1425, 'tipo': 'EMOLUMENTOS CONSULARES - PAÍS'},
     {'codigo': 1433, 'tipo': 'EMOLUMENTOS JUSTIÇA DISTRITO FEDERAL'},
     {'codigo': 1441, 'tipo': 'CONVÊNIOS - DEVOLUÇÃO DE SALDO'},
     {'codigo': 1484, 'tipo': 'TAXA JUDICIAL DA JUSTIÇA DO DISTRITO FEDERAL'},
     {'codigo': 1492, 'tipo': 'CUSTAS JUSTIÇA DISTRITO FEDERAL'}, {'codigo': 1505, 'tipo': 'CUSTAS JUDICIAIS - OUTRAS'},
     {'codigo': 1513, 'tipo': 'RECEITA DÍVIDA ATIVA - CUSTAS JUDICIAIS'},
     {'codigo': 1526, 'tipo': 'CONTRIBUIÇÃO SOBRE A RECEITA DE CONCURSOS E PROGNÓSTICOS - INDESP'},
     {'codigo': 1541, 'tipo': 'CONTRIBUIÇÃO DO ADICIONAL SOBRE A RECEITA DE CONCURSOS E PROGNÓSTICOS - INDESP'},
     {'codigo': 1548, 'tipo': 'TAXA DE FISCALIZAÇÃO DE PRODUTOS SOB CONTROLE DO MINISTÉRIO DO EXÉRCITO'},
     {'codigo': 1556, 'tipo': 'CONTRIBUIÇÃO PARA CUSTEIO DAS PENSÕES MILITARES'},
     {'codigo': 1572, 'tipo': 'MONTEPIO CIVIL'},
     {'codigo': 1599, 'tipo': 'IRPJ - PJ OBRIGADAS AO LUCRO REAL – ENTIDADES FINANCEIRAS – BALANÇO TRIMESTRAL'},
     {'codigo': 1607, 'tipo': 'MULTA POR ATERRO IRREGULAR - SPU'},
     {'codigo': 1635, 'tipo': 'CPSSS - CONTRIBUIÇÃO DO SERVIDOR CIVIL ATIVO'},
     {'codigo': 1652, 'tipo': 'TAXA PARA CERTIDÃO QUITAÇÃO CLT'}, {'codigo': 1800, 'tipo': 'IRPJ - FINOR'},
     {'codigo': 1804, 'tipo': 'RECEITA DÍVIDA ATIVA - CSLL'}, {'codigo': 1825, 'tipo': 'IRPJ - FINAM'},
     {'codigo': 1838, 'tipo': 'IRPJ - FUNRES'},
     {'codigo': 1866, 'tipo': 'ALIENAÇÃO OUTROS BENS MÓVEIS - PROGRAMA NACIONAL DE DESESTATIZAÇÃO'},
     {'codigo': 1879, 'tipo': 'ALIENAÇÃO TÍTULOS MOBILIÁRIOS - PROGRAMA NACIONAL DE DESESTATIZAÇÃO'},
     {'codigo': 1881, 'tipo': 'MULTAS PREVISTAS NA LEGISLAÇÃO DE TRANSITO'},
     {'codigo': 8551, 'tipo': 'CPSSS - CONTRIBUIÇÃO PATRONAL PARA O MILITAR'},
     {'codigo': 1894, 'tipo': 'RECEITA DÍVIDA ATIVA - ADICIONAL AO FRETE PARA RENOVAÇÃO DA MARINHA MERCANTE'},
     {'codigo': 1934, 'tipo': 'INDENIZAÇÃO ITAIPÚ - PARCELAS VINCENDAS'},
     {'codigo': 1962, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - PETRÓLEO E DERIVADOS'},
     {'codigo': 2030, 'tipo': 'CSLL - ENTIDADES FINANCEIRAS - BALANÇO TRIMESTRAL'},
     {'codigo': 2048, 'tipo': 'RENDA LÍQUIDA DA LOTERIA FEDERAL INSTANTÂNEA'}, {'codigo': 2049, 'tipo': 'ALUGUÉIS'},
     {'codigo': 2050, 'tipo': 'ITR - TAXA DE CADASTRO CONTRIBUIÇÕES ÁREA RURAL'},
     {'codigo': 2057, 'tipo': 'ARRENDAMENTOS'}, {'codigo': 2073, 'tipo': 'FOROS'},
     {'codigo': 2081, 'tipo': 'LAUDÊMIOS'}, {'codigo': 2090, 'tipo': 'TAXA DE OCUPAÇÃO DE IMÓVEIS - OUTROS'},
     {'codigo': 2102, 'tipo': 'OUTRAS RECEITAS IMOBILIÁRIAS'},
     {'codigo': 2129, 'tipo': 'RECEITA DÍVIDA ATIVA - TAXA FISCALIZAÇÃO TELECOMUNICAÇÕES'},
     {'codigo': 2157, 'tipo': 'RECEITA DE DÍVIDA ATIVA - ITR E RECEITAS VINCULADAS - EXERCÍCIO DE'},
     {'codigo': 2160, 'tipo': 'FUNDAF - SELOS ESPECIAIS - CIGARROS'},
     {'codigo': 2170, 'tipo': 'MULTA POR ATRASO NA ENTREGA DA DIRF ANUAL'},
     {'codigo': 2217, 'tipo': 'JUROS TÍTULOS DE RENDA - OUTROS'}, {'codigo': 2241, 'tipo': 'DIVIDENDOS - BANCOS'},
     {'codigo': 2250, 'tipo': 'DIVIDENDOS - OUTRAS SOCIEDADES DE ECONOMIA MISTA'},
     {'codigo': 2253, 'tipo': 'CONTRIBUIÇÃO AO FUNDO NACIONAL DA CULTURA - SOBRE PRÊMIOS E SORTEIOS'},
     {'codigo': 2268, 'tipo': 'DIVIDENDOS - EMPRESAS PUBLICAS'}, {'codigo': 2276, 'tipo': 'PARTICIPAÇÕES'},
     {'codigo': 2279, 'tipo': 'ITR - UNIÃO'},
     {'codigo': 8645, 'tipo': 'COFINS - FABRIC/IMPORT. VEICULOS - SUBS. TRIBUTARIA'},
     {'codigo': 8496, 'tipo': 'PIS - FABRIC/IMPORT VEIC. EM SUBST. TRIBUTÁRIA'},
     {'codigo': 2294, 'tipo': 'RECEITA DÍVIDA ATIVA - SPU'}, {'codigo': 2306, 'tipo': 'ITR - PREFEITURA'},
     {'codigo': 2313, 'tipo': 'JUROS BANCÁRIOS'},
     {'codigo': 2319, 'tipo': 'IRPJ - PJ OBRIGADAS AO LUCRO REAL - ENTIDADES FINANCEIRAS - ESTIMATIVA MENSAL'},
     {'codigo': 2321, 'tipo': 'OUTRAS RECEITAS PATRIMONIAIS'},
     {'codigo': 2347, 'tipo': 'SERVIÇOS ADMINISTRATIVOS - CADASTRO ITR'},
     {'codigo': 2375, 'tipo': 'CONTRIBUIÇÃO PARAFISCAL ITR'},
     {'codigo': 2390, 'tipo': 'IRPJ - PJ OBRIGADAS AO LUCRO REAL - ENTIDADES FINANCEIRAS - DECLARAÇÃO DE AJUSTE'},
     {'codigo': 2402, 'tipo': 'CONTRIBUIÇÃO CNA SINDICATO'},
     {'codigo': 2430, 'tipo': 'IRPJ - PJ OBRIGADAS AO LUCRO REAL-ENTIDADES NÃO FINANCEIRAS-DECLARAÇÃO DE AJUSTE'},
     {'codigo': 2443, 'tipo': 'CONTRIBUIÇÃO CNA FEDERAÇÃO'},
     {'codigo': 2456, 'tipo': 'IRPJ - PJ NÃO OBRIGADAS AO LUCRO REAL - DECLARAÇÃO DE AJUSTE'},
     {'codigo': 2469, 'tipo': 'CSLL - ENTIDADES FINANCEIRAS - ESTIMATIVA MENSAL'},
     {'codigo': 2471, 'tipo': 'CONTRIBUIÇÃO CNA CONFEDERAÇÃO'},
     {'codigo': 2509, 'tipo': 'CONTRIBUIÇÃO CNA/CONTAG MIN. TRABALHO'},
     {'codigo': 2552, 'tipo': 'CONTRIBUIÇÃO CNA/CONTAG PARCELA UNIÃO'},
     {'codigo': 2578, 'tipo': 'CONDECINE - CONTRIBUIÇÃO DESENVOLVIMENTO INDÚSTRIA CINEMA NACIONAL'},
     {'codigo': 2580, 'tipo': 'CONTRIBUIÇÃO CONTAG SINDICATO'}, {'codigo': 2583, 'tipo': 'MULTA DA SUSEP'},
     {'codigo': 2593, 'tipo': 'REMUNERAÇÃO DE BANCOS'}, {'codigo': 2618, 'tipo': 'CONTRIBUIÇÃO CONTAG FEDERAÇÃO'},
     {'codigo': 2655, 'tipo': 'COTA PARTE DO ADICIONAL AO FRETE PARA RENOVAÇÃO DA MARINHA MERCANTE -AFRMM'},
     {'codigo': 2659, 'tipo': 'CONTRIBUIÇÃO CONTAG CONFEDERAÇÃO'},
     {'codigo': 2663, 'tipo': 'SERVIÇOS ADMINISTRATIVOS - OUTROS'},
     {'codigo': 2671, 'tipo': 'OUTROS SERVIÇOS - DEMAIS'}, {'codigo': 2755, 'tipo': 'SERVIÇOS ADMINISTRATIVOS - DPRF'},
     {'codigo': 2768, 'tipo': 'IRPF - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 2783, 'tipo': 'IRPJ - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 2796, 'tipo': 'IPI - OUTROS - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 2808, 'tipo': 'IRRF - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 2810, 'tipo': 'IOF - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 2836, 'tipo': 'FINSOCIAL - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 2849, 'tipo': 'PIS - CONVERSÃO DE DEPÓSITO JUDICIAL'},
     {'codigo': 2851, 'tipo': 'CSLL - CONVERSÃO DE DEPÓSITO JUDICIAL'},
     {'codigo': 2877, 'tipo': 'MULTAS PREVISTAS NA LEGISLAÇÃO DO SEGURO DESEMPREGO E ABONO SALARIAL'},
     {'codigo': 2880, 'tipo': 'CONVERSÃO DEPÓSITO JUDICIAL - OUTROS'},
     {'codigo': 2890, 'tipo': 'MULTAS PREVISTAS NA LEGISLAÇÃO SANITÁRIA'},
     {'codigo': 2892, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2904, 'tipo': 'IRPF - LANÇAMENTO DE OFÍCIO'}, {'codigo': 2917, 'tipo': 'IRPJ - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2932, 'tipo': 'IRRF - LANÇAMENTO DE OFÍCIO'}, {'codigo': 2945, 'tipo': 'IPI - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2958, 'tipo': 'IOF - LANÇAMENTO DE OFÍCIO'}, {'codigo': 2960, 'tipo': 'COFINS - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2973, 'tipo': 'CSLL - LANÇAMENTO DE OFÍCIO'}, {'codigo': 2986, 'tipo': 'PIS - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2999, 'tipo': 'PASEP - LANÇAMENTO DE OFÍCIO'}, {'codigo': 3084, 'tipo': 'PASEP - RECEITA OPERACIONAL'},
     {'codigo': 3092, 'tipo': 'PASEP - FOLHA DE PAGAMENTO'},
     {'codigo': 3199, 'tipo': 'MULTA POR ATRASO NA ENTREGA DA DECLARAÇÃO DE IPI'},
     {'codigo': 3223, 'tipo': 'IRRF-RESGATE PREV COMPL/MOD CONTRIB DEF/VAR - NÃO OPT TRIB EXCLUS'},
     {'codigo': 3249, 'tipo': 'IRRF - OURO ATIVO FINANCEIRO/MUTUO/REVENDA'},
     {'codigo': 3251, 'tipo': 'IRRF - JUROS CADERNETA DE POUPANÇA E LETRAS HIPOTECÁRIAS - PESSOA JURÍDICA'},
     {'codigo': 3277, 'tipo': 'IRRF - RENDIMENTOS DE PARTES BENEFICIÁRIAS OU DE FUNDADOR'},
     {'codigo': 3292, 'tipo': 'FUNDAF - RESSARCIMENTO POR COPIAS XEROX'},
     {'codigo': 3304, 'tipo': 'FUNDAF - DEMAIS RECEITAS'}, {'codigo': 3317, 'tipo': 'IRPJ - RENDA VARIÁVEL'},
     {'codigo': 3320, 'tipo': 'IRPJ - LUCRO INFLACIONÁRIO'},
     {'codigo': 3345, 'tipo': 'IPI - VINCULADO IMPORTAÇÃO - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 3391, 'tipo': 'MULTA DE OUTRAS ORIGENS'},
     {'codigo': 3585, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO PARA O FUNTTEL'},
     {'codigo': 3426, 'tipo': 'IRRF - APLICAÇÕES FINANCEIRAS DE RENDA FIXA - PESSOA JURÍDICA'},
     {'codigo': 3441, 'tipo': 'DÍVIDA ATIVA GLOBAL'}, {'codigo': 3454, 'tipo': 'ENCARGOS DA DÍVIDA ATIVA GLOBAL'},
     {'codigo': 3467, 'tipo': 'IOF - SEGUROS'},
     {'codigo': 3471, 'tipo': 'MULTAS PREVISTAS NO CÓDIGO ELEITORAL E LEIS CONEXAS'},
     {'codigo': 3498, 'tipo': 'INDENIZAÇÕES - DEMAIS'},
     {'codigo': 3510, 'tipo': 'HONORÁRIOS DA DEFESA DA FAZENDA NACIONAL - GLOBAL'},
     {'codigo': 3527, 'tipo': 'RECEITA DÍVIDA ATIVA - IMPOSTO IMPORTAÇÃO'},
     {'codigo': 3543, 'tipo': 'RECEITA DÍVIDA ATIVA - IRPF'}, {'codigo': 3548, 'tipo': 'IRPJ - COBRANÇA'},
     {'codigo': 3550, 'tipo': 'IRRF - RENDIMENTO DO TRABALHO - COBRANÇA'},
     {'codigo': 3551, 'tipo': 'RECEITA DÍVIDA ATIVA - IRPJ'}, {'codigo': 3560, 'tipo': 'RECEITA DÍVIDA ATIVA - IRRF'},
     {'codigo': 3563, 'tipo': 'IRRF - RENDIMENTOS DE CAPITAL - COBRANÇA'},
     {'codigo': 3576, 'tipo': 'IRRF - OUTROS RENDIMENTOS - COBRANÇA'},
     {'codigo': 3578, 'tipo': 'RECEITA DÍVIDA ATIVA - IPI'}, {'codigo': 3589, 'tipo': 'IPI - BEBIDAS - COBRANÇA'},
     {'codigo': 3591, 'tipo': 'IPI - OUTROS - COBRANÇA'},
     {'codigo': 3594, 'tipo': 'MULTAS PREVISTAS NO REGISTRO DE ESTRANGEIROS'},
     {'codigo': 3603, 'tipo': 'IOF - COBRANÇA'}, {'codigo': 3607, 'tipo': 'RESTITUIÇÕES - OUTRAS'},
     {'codigo': 3615, 'tipo': 'RECEITA DÍVIDA ATIVA - OUTROS TRIBUTOS - PRINCIPAL'},
     {'codigo': 3616, 'tipo': 'PIS - COBRANÇA'}, {'codigo': 3623, 'tipo': 'RECEITA DÍVIDA ATIVA - MULTA CLT'},
     {'codigo': 3629, 'tipo': 'PASEP - COBRANÇA'}, {'codigo': 3640, 'tipo': 'RECEITA DÍVIDA ATIVA - OUTRAS'},
     {'codigo': 3644, 'tipo': 'COFINS - COBRANÇA'}, {'codigo': 3657, 'tipo': 'CSLL - COBRANÇA'},
     {'codigo': 3690, 'tipo': 'RECEITA DECORRENTE DE BENS E VALORES APREENDIDOS - OUTROS'},
     {'codigo': 3703, 'tipo': 'PASEP - PESSOA JURÍDICA DE DIREITO PUBLICO'},
     {'codigo': 3738, 'tipo': 'MULTAS DIVERSAS APLICADAS PELA RECEITA FEDERAL, EXCETO ADUANEIRA'},
     {'codigo': 3762, 'tipo': 'OUTRAS RECEITAS EVENTUAIS'}, {'codigo': 3885, 'tipo': 'PIS - RECEITA OPERACIONAL'},
     {'codigo': 3890, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 3914, 'tipo': 'PARCELAMENTO - IMÓVEIS EXTINTA RFFSA - SPU'},
     {'codigo': 3928, 'tipo': 'IPI - VINCULADO IMPORTAÇÃO - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 3981, 'tipo': 'PRODUTO DEPÓSITOS ABANDONADOS'}, {'codigo': 4028, 'tipo': 'IOF - OURO ATIVO FINANCEIRO'},
     {'codigo': 4181, 'tipo': 'IRPF - COBRANÇA'}, {'codigo': 4221, 'tipo': 'IPMF - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 4234, 'tipo': 'COFINS - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 4250, 'tipo': 'ANEEL - PARCELAS DA RESERVA GLOBAL DE REVERSÃO'},
     {'codigo': 4262, 'tipo': 'MULTA APLICADA À REDE - NE 015/93'},
     {'codigo': 4275, 'tipo': 'CPSSS - CONTRIBUIÇÃO PATRONAL PARA O SERVIDOR CIVIL'},
     {'codigo': 4288, 'tipo': 'MULTA POR NOTA FISCAL'},
     {'codigo': 4290, 'tipo': 'IOF - OPERAÇÕES DE CAMBIO - ENTRADA DE MOEDA'},
     {'codigo': 4298, 'tipo': 'ALIENAÇÃO OUTROS BENS MÓVEIS - OUTROS'},
     {'codigo': 4300, 'tipo': 'ALIENAÇÃO DO DOMÍNIO ÚTIL DE BENS IMÓVEIS - SPU'},
     {'codigo': 4327, 'tipo': 'ALIENAÇÃO DO DOMÍNIO PLENO DE BENS IMÓVEIS - SPU'},
     {'codigo': 4335, 'tipo': 'ALIENAÇÃO OUTROS BENS IMÓVEIS - DEMAIS'},
     {'codigo': 4371, 'tipo': 'IRRF-RENDIMENTOS PAGOS PELA ADMINISTRAÇÃO DIRETA,FUNDAÇÕES E AUTARQUIAS FEDERAIS'},
     {'codigo': 4394, 'tipo': 'AMORTIZAÇÕES DE EMPRÉSTIMOS'},
     {'codigo': 4490, 'tipo': 'ALIENAÇÃO TÍTULOS MOBILIÁRIOS - OUTROS'},
     {'codigo': 4493, 'tipo': 'RECEITA DÍVIDA ATIVA - COFINS'},
     {'codigo': 4533, 'tipo': 'RECEITA DÍVIDA ATIVA - PROEX'},
     {'codigo': 4570, 'tipo': 'ENCARGOS POR RECOLHIMENTO FORA DO PRAZO'},
     {'codigo': 4574, 'tipo': 'PIS - ENTIDADES FINANCEIRAS E EQUIPARADAS'},
     {'codigo': 4600, 'tipo': 'IRPF - GANHOS DE CAPITAL NA ALIENAÇÃO DE BENS DURÁVEIS'},
     {'codigo': 4601, 'tipo': 'COTA PARTE - PREÇO DE REALIZAÇÃO DE COMBUSTÍVEL'},
     {'codigo': 4614, 'tipo': 'CONVERSÃO DEPÓSITO JUDICIAL - ADICIONAL AO FRETE PARA RENOVAÇÃO MARINHA MERCANTE'},
     {'codigo': 4634, 'tipo': 'DEVOLUCAO REST NAO PAGAS IRPF'}, {'codigo': 4677, 'tipo': 'RESTITUIÇÕES - IPI'},
     {'codigo': 4810, 'tipo': 'RESSARCIMENTO FINANCEIRO - DEC 97459'},
     {'codigo': 5014, 'tipo': 'ITR - PREFEITURAS - EXERCÍCIOS ANTERIORES'},
     {'codigo': 5020, 'tipo': 'OUTROS SERVIÇOS COMERCIAIS'},
     {'codigo': 5027, 'tipo': 'ITR - UNIÃO - EXERCÍCIOS ANTERIORES'}, {'codigo': 5135, 'tipo': 'TRIBUTOS EXTINTOS'},
     {'codigo': 5160, 'tipo': 'SALDOS DE RECEITAS EXCLUÍDAS'},
     {'codigo': 5164, 'tipo': 'CONTRIBUIÇÃO SOBRE A RECEITA DE CONCURSOS E PROGNÓSTICOS - FUNDO PENITENCIÁRIO'},
     {'codigo': 8470, 'tipo': 'R D ATIVA - MULTA CRIMINAL/JUSTIÇA FEDERAL'},
     {'codigo': 5177, 'tipo': 'INDENIZAÇÕES - AGU'},
     {'codigo': 5180, 'tipo': 'HONORÁRIOS ADVOCATÍCIOS SUCUMBENCIA - AGU'},
     {'codigo': 5192, 'tipo': 'IRRF - OBRAS AUDIOV CINEM/VIDEOF (LEI 8.685/93) - RES EXT'},
     {'codigo': 5204, 'tipo': 'IRRF - JUROS INDENIZAÇÕES LUCROS CESSANTES'},
     {'codigo': 5217, 'tipo': 'IRRF - PAGAMENTO A BENEFICIÁRIO NÃO IDENTIFICADO'},
     {'codigo': 5220, 'tipo': 'IOF - OPERAÇÕES DE CÂMBIO'},
     {'codigo': 5232, 'tipo': 'IRRF - APLICAÇÕES FINANCEIRAS EM FUNDOS DE INVESTIMENTO IMOBILIÁRIO'},
     {'codigo': 5260, 'tipo': 'OUTRAS RECEITAS - FUNPEM'},
     {'codigo': 5273, 'tipo': 'IRRF - OPERAÇÕES DE SWAP (ART. 74 L 8981/95)'},
     {'codigo': 5286, 'tipo': 'IRRF - APLICAÇÕES FINANCEIRAS DE RESIDENTES NO EXTERIOR (ART. 81 L. 8981/95)'},
     {'codigo': 5299, 'tipo': 'IRRF - JUROS SOBRE EMPRÉSTIMOS EXTERNOS (DL 2303/86)'},
     {'codigo': 5300, 'tipo': 'MULTA ATRASO ENTREGA DECLARAÇÃO ITR'},
     {'codigo': 5303, 'tipo': 'RECEITA DÍVIDA ATIVA - IMPOSTOS EXTINTOS'},
     {'codigo': 5320, 'tipo': 'MULTA ATRASO ENTREGA DIRPF'}, {'codigo': 5338, 'tipo': 'MULTA ATRASO ENTREGA DIRPJ'},
     {'codigo': 5382, 'tipo': 'RECEITA DÍVIDA ATIVA - OUTRAS MULTAS'},
     {'codigo': 5395, 'tipo': 'RECEITA DÍVIDA ATIVA - IMPOSTO EXPORTAÇÃO'},
     {'codigo': 5422, 'tipo': 'RECEITA DÍVIDA ATIVA - IPMF'},
     {'codigo': 5503, 'tipo': 'IPI - VINCULADO IMPORTAÇÃO VEÍCULOS'},
     {'codigo': 5506, 'tipo': 'OUTRAS CONTRIBUIÇÕES ECONÔMICAS'},
     {'codigo': 5516, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - VEÍCULOS'},
     {'codigo': 5572, 'tipo': 'MULTA DISTRIBUIÇÃO DE PRÊMIO (S/REDUÇÃO)'},
     {'codigo': 5585, 'tipo': 'MULTA SEGURANÇA PRIVADA - DPF (LEI 9.017/95)'},
     {'codigo': 5610, 'tipo': 'SERVIÇOS FINANCEIROS - OUTROS'}, {'codigo': 5612, 'tipo': 'OUTROS SERVIÇOS - MICT'},
     {'codigo': 5625, 'tipo': 'IRPJ - LUCRO ARBITRADO'}, {'codigo': 5638, 'tipo': 'CSLL - LUCRO ARBITRADO'},
     {'codigo': 5640, 'tipo': 'TRANSFERENCIAS DE PESSOAS - FUNDO PARTIDÁRIO'},
     {'codigo': 520, 'tipo': 'PARCELAMENTO INSTITUIÇÕES DE ENSINO SUPERIOR - LEI Nº 10.260/01'},
     {'codigo': 3148, 'tipo': 'MULTA ISOLADA - CRÉDITO PEDIDO RESSARCIM/DECLARAÇÃO COMPENSAÇÃO'},
     {'codigo': 842, 'tipo': 'PARCELAMENTO ART. 1º MP 303/2006 - DEMAIS PESSOAS JURÍDICAS'},
     {'codigo': 445, 'tipo': 'R D ATIVA - FUNCAFÉ - LEILÃO'},
     {'codigo': 474, 'tipo': 'COFINS - IMPORTAÇÃO - CONTRIBUIÇÃO NÃO PAGA DEVIDO SUSPENSÃO'},
     {'codigo': 594, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DASN'},
     {'codigo': 390, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DIMOF'},
     {'codigo': 627, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DEREX'},
     {'codigo': 662, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DPREV'},
     {'codigo': 873, 'tipo': 'PARCELAMENTO PARA INGRESSO NO SIMPLES NACIONAL - 2009'},
     {'codigo': 970, 'tipo': 'R D ATIVA - PARCELAMENTO PARA INGRESSO NO SIMPLES NACIONAL - 2009'},
     {'codigo': 610, 'tipo': 'IRRF - TRANSPORTE RODOVIARIO INTERN CARGA-PG PJ A PF-PARAGUAI'},
     {'codigo': 691, 'tipo': 'PIS - TRIBUTAÇÃO DE BEBIDAS FRIAS - DEMAIS BEBIDAS'},
     {'codigo': 724, 'tipo': 'PIS IMPORTAÇÃO - TRIBUTAÇÃO DE BEBIDAS FRIAS - CERVEJAS'},
     {'codigo': 753, 'tipo': 'PIS IMPORTAÇÃO -TRIBUTAÇÃO DE BEBIDAS FRIAS - DEMAIS BEBIDAS'},
     {'codigo': 760, 'tipo': 'COFINS - TRIBUTAÇÃO DE BEBIDAS FRIAS - CERVEJAS'},
     {'codigo': 776, 'tipo': 'COFINS - TRIBUTAÇÃO DE BEBIDAS FRIAS - DEMAIS BEBIDAS'},
     {'codigo': 782, 'tipo': 'COFINS IMPORTAÇÃO - TRIBUTAÇÃO DE BEBIDAS FRIAS - CERVEJAS'},
     {'codigo': 867, 'tipo': 'IPI VINCULADO A IMPORTAÇÃO-TRIBUTAÇ��O BEBIDAS FRIAS-DEMAIS BEBIDAS'},
     {'codigo': 906, 'tipo': 'PIS - REGIME ESPECIAL DE APURAÇÃO E PAGAMENTO - ÁLCOOL'},
     {'codigo': 701, 'tipo': 'PARCELAMENTO - ART 1º DA MP 303/2006 - DEPÓSITO JUDICIAL'},
     {'codigo': 1068, 'tipo': 'PAGAMENTO UNIFICADO - PMCMV/CONSTR OU REFORMA DE CRECHE/PRÉ-ESCOLA'},
     {'codigo': 1107, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA GFIP'},
     {'codigo': 1136, 'tipo': 'LEI 11.941/09-PGFN-DEB PREV-PARCELAMENTO ART. 1º'},
     {'codigo': 1194, 'tipo': 'LEI 11.941/09-PGFN-DEMAIS DEB-PARCELAMENTO ART. 1º'},
     {'codigo': 1210, 'tipo': 'LEI 11.941/09-PGFN-PARCELAMENTO APROV INDEVIDO CRED IPI-ART. 2º'},
     {'codigo': 559, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DERC'},
     {'codigo': 935, 'tipo': 'COFINS-IMPORTAÇÃO-REGIME ESPECIAL DE APURAÇÃO E PAGAMENTO - ÁLCOOL'},
     {'codigo': 941, 'tipo': 'PAGAMENTO/PARCELAMENTO - ART. 1º DA MP 449/2008'},
     {'codigo': 987, 'tipo': 'PAGAMENTO/PARCELAMENTO - ART. 2º MP 449/08'},
     {'codigo': 1171, 'tipo': 'LEI 11.941/09-PGFN-DEB PREV-PG C/ PREJ FISCAL E BC NEG CSLL'},
     {'codigo': 1204, 'tipo': 'LEI 11.941/09-PGFN-DEMAIS DEB-PARCELAMENTO ART. 3º'},
     {'codigo': 1233, 'tipo': 'LEI 11.941/09-RFB-DEB PREV-PARCELAMENTO ART. 1º'},
     {'codigo': 1240, 'tipo': 'LEI 11.941/09-RFB-DEB PREV-PARCELAMENTO ART. 3º'},
     {'codigo': 1113, 'tipo': 'IRPJ - SIMPLES NACIONAL - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 1318, 'tipo': 'IPI - SIMPLES NACIONAL - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 1324, 'tipo': 'CSLL - SIMPLES NACIONAL - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 1360, 'tipo': 'CONTRIBUIÇÃO PATRONAL PREVIDENCIÁRIA-SIMPLES NACIONAL-LANÇ OFÍCIO'},
     {'codigo': 1376, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DIF - PAPEL IMUNE'},
     {'codigo': 1382, 'tipo': 'LEI 11.941/2009 - PGFN - DEB PREVID - PARCEL - ART.1º - DEP JUD'},
     {'codigo': 1399, 'tipo': 'LEI 11.941/2009 - PGFN-DEMAIS DÉBITOS - PARCEL - ART. 1º - DEP JUD'},
     {'codigo': 1415, 'tipo': 'LEI 11.941/09 - RFB - DEBITOS PREVID - PARCEL - ART. 1º - DEP JUD'},
     {'codigo': 1421, 'tipo': 'LEI 11.941/09 - RFB - DEMAIS DÉBITOS - PARCEL - ART.1º - DEP JUD'},
     {'codigo': 1438, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA ECD'},
     {'codigo': 1444, 'tipo': 'PAGAGMENTO/PARCELAMENTO - MP 470/2009 - RFB'},
     {'codigo': 52, 'tipo': 'REGULARIZAÇÃO DEPÓSITO EXTRAJUDICIAL NÃO TRIBUTÁRIO - L. 12.099/09'},
     {'codigo': 1467, 'tipo': 'REGULARIZAÇÃO DEPÓSITO JUDICIAL NÃO TRIBUTÁRIO - LEI 12.099/2009'},
     {'codigo': 1496, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - IRPJ - NÃO TRIBUTÁRIO'},
     {'codigo': 1529, 'tipo': 'R D ATIVA - FUNDO DE TERRAS E DA REFORMA AGRÁRIA'},
     {'codigo': 30, 'tipo': 'ALIENAÇÃO DO DOMÍNIO DIRETO - SPU'}, {'codigo': 46, 'tipo': 'PERMISSÃO DE USO - SPU'},
     {'codigo': 1256, 'tipo': 'LEI 11.941/09-RFB-DEB PREV-PG C/ PREJ FISCAL E BC NEG CSLL'},
     {'codigo': 1262, 'tipo': 'LEI 11.941/09-RFB-DEMAIS DEB-PG C/ PREJ FISCAL E BC NEG CSLL'},
     {'codigo': 1279, 'tipo': 'LEI 11.941/09-RFB-DEMAIS DEB-PARCELAMENTO ART. 1º'},
     {'codigo': 1285, 'tipo': 'LEI 11.941/09-RFB-DEMAIS DEBITOS-PARCELAMENTO ART. 3º'},
     {'codigo': 1291, 'tipo': 'LEI 11.941/09-RFB-PARCELAMENTO APROV INDEVIDO CRED IPI - ART. 2º'},
     {'codigo': 1506, 'tipo': 'MULTA POR ATRASO NA ENTREGA DA DASN - SIMEI'},
     {'codigo': 1558, 'tipo': 'MULTA ADUANEIRA - REMESSA EXPRESSA'},
     {'codigo': 1512, 'tipo': 'MULTA POR ATRASO NA ENTREGA DO FCONT'}, {'codigo': 69, 'tipo': 'CESSÃO DE USO - SPU'},
     {'codigo': 1632, 'tipo': 'MULTA POR NÃO RECOLHIMENTO DA ESTIMATIVA - IRPJ'},
     {'codigo': 1649, 'tipo': 'MULTA POR NÃO RECOLHIMENTO DA ESTIMATIVA - CSLL'},
     {'codigo': 1661, 'tipo': 'CPSS - SERVIDOR CIVIL ATIVO'},
     {'codigo': 1684, 'tipo': 'CPSS - SERVIDOR CIVIL LICENCIADO/AFASTADO'},
     {'codigo': 1690, 'tipo': 'CPSS - DECISÃO JUDICIAL MANDADO DE SEGURANÇA'},
     {'codigo': 1700, 'tipo': 'CPSS - SERVIDOR CIVIL INATIVO'}, {'codigo': 1717, 'tipo': 'CPSS - PENSIONISTA CIVIL'},
     {'codigo': 1730, 'tipo': 'CPSS - SERVIDOR CIVIL INATIVO - PRECATÓRIO/REQUISIÇ PEQUENO VALOR'},
     {'codigo': 1781, 'tipo': 'CPSS - PATRONAL - SERV CIVIL LICENCIADO/AFAST - OP INTRA-ORÇAMENT'},
     {'codigo': 1808, 'tipo': 'CPSS - PATRONAL - DECISÃO JUD MAND SEGURANÇA -OPER INTRA-ORÇAMENT'},
     {'codigo': 1814, 'tipo': 'CPSS - PATRONAL - SERVIDOR NO EXTERIOR -OPER INTRA-ORÇAMENT'},
     {'codigo': 1837, 'tipo': 'CPSS - PATRONAL - PRECATÓRIO/ REQ PEQ VALOR - INTRA-ORÇAMENTÁRIA'},
     {'codigo': 1843, 'tipo': 'R D ATIVA - CONTRIB PLANO SEGURID SOC SERV PÚB - CPSS - PATRONAL'},
     {'codigo': 1911, 'tipo': 'R D ATIVA - CONTRIB PLANO SEG SOC SERV PÚB - CPSS - NÃO PATRONAL'},
     {'codigo': 1850, 'tipo': 'CONTRIB PLANO SEG SOC SERV PÚBLICO- CPSS - PATRONAL - LANÇ OFÍCIO'},
     {'codigo': 1928, 'tipo': 'CONT PLANO SEG SOC SERV PÚB - CPSS - NÃO PATRONAL - LANÇ OFÍCIO'},
     {'codigo': 1626, 'tipo': 'MULTA POR ATRASO NA ENTREGA DA DECLARAÇÃO SERVIÇOS MÉDICOS - DMED'},
     {'codigo': 1330, 'tipo': 'COFINS - SIMPLES NACIONAL - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 1347, 'tipo': 'PIS - SIMPLES NACIONAL - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 1480, 'tipo': 'R D ATIVA - PAGAMENTO/PARCELAMENTO - MP 470/2009 - PGFN'},
     {'codigo': 1593, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - REMESSA EXPRESSA - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 1535, 'tipo': 'R D ATIVA - FUNCAFÉ - DAÇÃO EM PAGAMENTO'},
     {'codigo': 1752, 'tipo': 'CPSS - PENSIONISTA - PRECATÓRIO JUDICIAL/REQUISIÇÃO PEQUENO VALOR'},
     {'codigo': 1957, 'tipo': 'DIREITOS DE NATUREZA COMERCIAL'},
     {'codigo': 1963, 'tipo': 'DIREITOS DE NATUREZA COMERCIAL - LANÇAMENTO DE OFICIO'},
     {'codigo': 1889, 'tipo': 'IRRF - RENDIMENTOS ACUMULADOS - ART. 12-A LEI Nº 7.713/1988'},
     {'codigo': 1895, 'tipo': 'IRRF - REND DECOR DECISÃO JUSTIÇA EST/DF, EXCETO ART 12A L 7713/88'},
     {'codigo': 2015, 'tipo': 'R D ATIVA - CRÉDITO RURAL - SECURITIZAÇÃO'},
     {'codigo': 2021, 'tipo': 'R D ATIVA - CRÉDITO RURAL - PROGRAMA ESPECIAL SANEAMENTO ATIVOS'},
     {'codigo': 2038, 'tipo': 'R D ATIVA - CRÉDITO RURAL - PROG DESENVOLV CERRADO - PRODECER II'},
     {'codigo': 2044, 'tipo': 'R D ATIVA - CRÉDITO RURAL -PROGRAMA NAC FORTALEC AGRICULT FAMILIAR'},
     {'codigo': 2067, 'tipo': 'R D ATIVA - CRÉDITO RURAL - PROG RECUPERAÇÃO LAVOURA CACAU BAIANA'},
     {'codigo': 2009, 'tipo': 'R D ATIVA - MULTA PROCESSUAL PENAL - TJDF'},
     {'codigo': 2080, 'tipo': 'DEPÓSITOS JUDICIAIS E EXTRAJUDICIAIS ADMINISTRADOS PELA PGF-AGU'},
     {'codigo': 2865, 'tipo': 'R D ATIVA - CRÉDITO RURAL - PROG REVIT COOP PRODUÇÃO AGROP- RECOOP'},
     {'codigo': 2203, 'tipo': 'MULTA POR ATRASO NA ENTREGA DA EFD-CONTRIBUIÇÕES'},
     {'codigo': 2096, 'tipo': 'CONTRIBUIÇÃO SEGURADOS - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2249, 'tipo': 'CONTRIB OUTRAS ENTIDADES/FUNDOS - INCRA - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2261, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - FDEPM -LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2290, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SEST - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2317, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAI- LANÇAMENTO DE OFÍCIO'},
     {'codigo': 81, 'tipo': 'INDENIZAÇÃO POR POSSE/OCUPAÇÃO ILÍCITA - SPU'},
     {'codigo': 1723, 'tipo': 'CPSS - SERVIDOR CIVIL ATIVO - PRECATÓRIO/REQUISIÇÃO PEQUENO VALOR'},
     {'codigo': 2141, 'tipo': 'CONTRIBUIÇÃO EMPRESA/EMPREGADOR- LANÇAMENTO OFÍCIO'},
     {'codigo': 2158, 'tipo': 'CONTRIBUIÇÃO RISCOS AMBIENTAIS/APOSENTADORIA ESPECIAL - LANÇ OF'},
     {'codigo': 2193, 'tipo': 'CONTRIBUIÇÃO SUJEITA A RETENÇÃO PREVIDENCIÁRIA - LANÇ DE OFÍCIO'},
     {'codigo': 2414, 'tipo': 'GLOSA DE COMPENSAÇÃO PREVIDENCIÁRIA - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2398, 'tipo': 'MULTA ISOLADA COMPENSAÇÃO PREVIDENCIÁRIA INDEVIDA'},
     {'codigo': 2226, 'tipo': 'CONTRIBUIÇÃO SEGURADO - DEPÓSITO JUDICIAL'},
     {'codigo': 2592, 'tipo': 'CIDE - CONTR OUTRAS ENTIDADE/FUNDO -SEBRAE/APEX/ABDI -DEP JUDICIAL'},
     {'codigo': 2602, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESCOOP - DEPÓSITO JUDICIAL'},
     {'codigo': 2654, 'tipo': 'MULTA ISOLADA PREVIDENCIÁRIA - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 2677, 'tipo': 'CONTRIB OUTRAS ENTIDADES/FUNDOS - SALÁRIO EDUCAÇÃO - DEP ADMINIST'},
     {'codigo': 2683, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAR - DEPÓSITO ADMINIST'},
     {'codigo': 2716, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - INCRA - DEPÓSITO ADMINIST'},
     {'codigo': 2722, 'tipo': 'CONTRIB OUTRAS ENTIDADES/FUNDOS - FUNDO AEROVIÁRIO - DEP ADMINIST'},
     {'codigo': 2739, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - FDEPM - DEPÓSITO ADMINIST'},
     {'codigo': 2745, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAT - DEPÓSITO ADMINIST'},
     {'codigo': 2774, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SEST - DEPÓSITO ADMINIST'},
     {'codigo': 2780, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAI - DEPÓSITO ADMINIST'},
     {'codigo': 2797, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESI - DEPÓSITO ADMINIST'},
     {'codigo': 2813, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAC - DEPÓSITO ADMINIST'},
     {'codigo': 2820, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESC - DEPÓSITO ADMINIST'},
     {'codigo': 2842, 'tipo': 'CIDE -CONTRIB OUTRA ENTIDADE/FUNDO -SEBRAE/APEX/ABDI -DEP ADMINIST'},
     {'codigo': 1769, 'tipo': 'CPSS - PATRONAL - SERVIDOR CIVIL ATIVO - OPER INTRA-ORÇAMENTÁRIA'},
     {'codigo': 2164, 'tipo': 'CONTRIB OUTRAS ENTIDADES/FUNDOS - SALÁRIO EDUCAÇÃO - LANÇ OFÍCIO'},
     {'codigo': 2187, 'tipo': 'CONTRIB OUTRAS ENTIDADES/FUNDOS - SENAR - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2255, 'tipo': 'CONTRIB OUTRAS ENTIDADES/FUNDOS - FUNDO AEROVIÁRIO- LANÇ DE OFÍCIO'},
     {'codigo': 2346, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAC- LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2450, 'tipo': 'CONTRIB OUTRAS ENTIDADES/FUNDOS - SALÁRIO EDUC - DEPÓSITO JUDICIAL'},
     {'codigo': 2466, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAR - DEPÓSITO JUDICIAL'},
     {'codigo': 2859, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESCOOP - DEPÓSITO ADMINIST'},
     {'codigo': 2927, 'tipo': 'IOF - CONTRATO DE DERIVATIVOS'},
     {'codigo': 1655, 'tipo': 'MULTA DO REGIME DISCIPLINAR APLICADA À RARP'},
     {'codigo': 3043, 'tipo': 'LEI 11.941/09-PGFN-PARCEL APROV INDEVIDO CRÉD IPI-ART.2º - DEP JUD'},
     {'codigo': 3140, 'tipo': 'R D ATIVA - CSLL - LANÇADO DE OFÍCIO - SIMPLES NACIONAL'},
     {'codigo': 3186, 'tipo': 'R D ATIVA - IPI - LANÇADO DE OFÍCIO - SIMPLES NACIONAL'},
     {'codigo': 3225, 'tipo': 'IRPJ - GANHOS LÍQUIDOS OPERAÇÕES NA BOLSA - SIMPLES NACIONAL'},
     {'codigo': 1394, 'tipo': 'II - BAGAGEM ACOMPANHADA CARTÃO CRÉDITO/DÉBITO'},
     {'codigo': 3254, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - REMESSA POSTAL - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 3300, 'tipo': 'CPSS - NÃO PATRONAL - DEPÓSITO JUDICIAL'},
     {'codigo': 3322, 'tipo': 'CPSS - NÃO PATRONAL - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 3351, 'tipo': 'DOAÇÕES AOS FUNDOS DOS DIREITOS DA CRIANÇA E DO ADOLESCENTE'},
     {'codigo': 3374, 'tipo': 'MULTA DO REGIME DISCIPLINAR APLICADA À RAS'},
     {'codigo': 3397, 'tipo': 'MULTA ADMINISTRATIVA POR FALTA DE PAGAMENTO EM LEILÃO'},
     {'codigo': 3399, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - II - NÃO TRIBUTÁRIO'},
     {'codigo': 7118, 'tipo': 'MULTA ADMINISTRATIVA POR INFRAÇÃO TRABALHISTA - DJE'},
     {'codigo': 1970, 'tipo': 'MULTA ISOLADA - § 6º DO ART 7º DA LEI Nº 12.270/2010'},
     {'codigo': 1992, 'tipo': 'MULTA ISOLADA - § 7º DO ART 7º DA LEI Nº 12.270/2010'},
     {'codigo': 3202, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO PREVIDENCIÁRIA SOBRE RECEITA BRUTA'},
     {'codigo': 3412, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - ITR - NÃO TRIBUTÁRIO'},
     {'codigo': 3436, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - IOF - NÃO TRIBUTÁRIO'},
     {'codigo': 3533, 'tipo': 'IRRF - APOSENTADORIA REGIME GERAL OU DO SERVIDOR PÚBLICO'},
     {'codigo': 3556, 'tipo': 'IRRF - RESGATE PREV COMPL/MOD BENEF DEF- NÃO OPTANTE TRIB EXCLUSIV'},
     {'codigo': 3579, 'tipo': 'IRRF - RESGATE PREVIDÊNCIA COMPLEMENTAR/OPTANTE TRIB EXCLUSIVA'},
     {'codigo': 3601, 'tipo': 'CONTRIBUIÇÃO PREVIDENCIÁRIA SOBRE RECEITA BRUTA - LANÇADA OFÍCIO'},
     {'codigo': 3618, 'tipo': 'COMPENSAÇÃO PREVIDENCIÁRIA INDEVIDA EM GFIP'},
     {'codigo': 3624, 'tipo': 'MULTA POR ATRASO NA ENTREGA DA ESCRITURAÇÃO CONTÁBIL FISCAL (ECF)'},
     {'codigo': 3647, 'tipo': 'ENCARGOS POR RECOLHIMENTO FORA DO PRAZO - DAE'},
     {'codigo': 3653, 'tipo': 'ENCARGOS REPASSE FORA PRAZO - IFC - DAE'},
     {'codigo': 3699, 'tipo': 'IRRF - TRIBUTAÇÃO EXCLUSIVA - ART. 2º DA LEI Nº 12.431/2011'},
     {'codigo': 3780, 'tipo': 'REABERTURA L 11941/09-PGFN-DÉB PREV- PARCEL DÍV NÃO PARC ANT-ART 1'},
     {'codigo': 3812, 'tipo': 'REABERTURA L11941/09- PGFN- DÉB PREV- PG À VISTA COM PF E BCN CSLL'},
     {'codigo': 3829, 'tipo': 'REABERTURA L11941/09- PGFN-DEMAIS DÉB-PG À VISTA COM PF E BCN CSLL'},
     {'codigo': 3841, 'tipo': 'REABERTURA LEI Nº 11.941, DE 2009 - PGFN - DEMAIS DÉBITOS - ART 3'},
     {'codigo': 3870, 'tipo': 'REABERTURA L 11941/09-RFB- DÉB PREV- PARCEL DÍV NÃO PARC ANT-ART 1'},
     {'codigo': 3887, 'tipo': 'REABERTURA LEI 11.941/09 - RFB - DÉBITOS PREVIDENCIÁRIOS - ART. 3'},
     {'codigo': 3910, 'tipo': 'REABERTURA L11941/09- RFB-DEMAIS DÉB- PG À VISTA COM PF E BCN CSLL'},
     {'codigo': 2278, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAT- LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2352, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESC - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2369, 'tipo': 'CIDE -CONTRIB OUTRAS ENTIDADE/FUNDO -SEBRAE/APEX/ABDI -LANÇ OFÍCIO'},
     {'codigo': 2381, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESCOOP - LANÇAMENTO OFÍCIO'},
     {'codigo': 2408, 'tipo': 'MULTA REGULAMENTAR DESCUMPRIMENTO OBRIG ACESSÓRIA PREVID - LANÇ OF'},
     {'codigo': 2420, 'tipo': 'MULTA ISOLADA PREVIDENCIÁRIA - DEPÓSITO JUDICIAL'},
     {'codigo': 2472, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - INCRA - DEPÓSITO JUDICIAL'},
     {'codigo': 2489, 'tipo': 'CONTRIB OUTRAS ENTIDADES/FUNDOS - FUNDO AEROVIÁRIO - DEP JUDICIAL'},
     {'codigo': 2505, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - FDEPM - DEPÓSITO JUDICIAL'},
     {'codigo': 2528, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAT - DEPÓSITO JUDICIAL'},
     {'codigo': 2534, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SEST - DEPÓSITO JUDICIAL'},
     {'codigo': 2557, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAI - DEPÓSITO JUDICIAL'},
     {'codigo': 2563, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESI - DEPÓSITO JUDICIAL'},
     {'codigo': 2570, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAC - DEPÓSITO JUDICIAL'},
     {'codigo': 2586, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESC - DEPÓSITO JUDICIAL'},
     {'codigo': 2933, 'tipo': 'REGIME DE TRIBUTAÇÃO UNIFICADA - RTU - IMPORTAÇÃO'},
     {'codigo': 2956, 'tipo': 'REGIME TRIBUTAÇÃO UNIFICADA - RTU - IMPORTAÇÃO - LANÇAMENTO OFÍCIO'},
     {'codigo': 1402, 'tipo': 'II -BAGAGEM ACOMP CARTÃO CRÉD/DÉB -LANÇADO DE OFÍCIO'},
     {'codigo': 3858, 'tipo': 'REABERTURA L11941/2009 - PGFN - APROV INDEVIDO CRÉDITO IPI - ART 2'},
     {'codigo': 3926, 'tipo': 'REABERTURA L 11941/09-RFB- DEMAIS DÉB- PARC DÍV NÃO PARC ANT-ART 1'},
     {'codigo': 4007, 'tipo': 'LEI Nº 12.865/2013 - RFB - PARCELAMENTO PIS/COFINS - ART 39, CAPUT'},
     {'codigo': 4013, 'tipo': 'LEI Nº 12865/2013 - PGFN - PARCELAMENTO PIS/COFINS - ART 39, CAPUT'},
     {'codigo': 4020, 'tipo': 'LEI Nº 12.865/2013 - RFB - PARCELAMENTO PIS/COFINS - ART. 39, § 1º'},
     {'codigo': 9440, 'tipo': 'IRPF - GANHOS LÍQUIDOS EM OPERAÇÕES NA BOLSA DE VALORES - OPÇÃO MP'},
     {'codigo': 9481, 'tipo': 'IRPJ-GANHOS LÍQ OPER BOLSA-PJ ISENTA OU SIMPLES-OPÇÃO MP 16/01'},
     {'codigo': 9004, 'tipo': 'IRPJ - FINOR - BALANÇO TRIMESTRAL - PESSOA JURÍDICA QUE ATENDA ÀS'},
     {'codigo': 9017, 'tipo': 'IRPJ - FINOR - ESTIMATIVA - PESSOA JURÍDICA QUE ATENDA ÀS CONDIÇÕ'},
     {'codigo': 9020, 'tipo': 'IRPJ - FINAM - BALANÇO TRIMESTRAL - PESSOA JURÍDICA QUE ATENDA ÀS'},
     {'codigo': 9032, 'tipo': 'IRPJ - FINAM - ESTIMATIVA - PESSOA JURÍDICA QUE ATENDA ÀS CONDIÇÕ'},
     {'codigo': 9045, 'tipo': 'IRPJ - FUNRES - BALANÇO TRIMESTRAL - PESSOA JURÍDICA QUE ATENDA À'},
     {'codigo': 9058, 'tipo': 'IRPJ - FUNRES - ESTIMATIVA - PESSOA JURÍDICA QUE ATENDA ÀS CONDIÇ'},
     {'codigo': 8960, 'tipo': 'IRPF - GANHO DE CAPITAL NA ALIENAÇÃO DE MOEDA ESTRANGEIRA MANTIDA'},
     {'codigo': 9479, 'tipo': 'MULTA POR ATRASO NA ENTREGA DA DECLARAÇÃO DA CPMF - IN 45/2001, AR'},
     {'codigo': 9438, 'tipo': 'CIDE-COMBUSTÍVEIS - IMPORTAÇÃO - LEI 10336/2001'},
     {'codigo': 9331, 'tipo': 'CIDE-COMBUSTÍVEIS - MERCADO INTERNO - LEI 10336/2001'},
     {'codigo': 9013, 'tipo': 'CONDECINE - PAGAMENTO, CRÉDITO, EMPREGO, ENTREGA E REMESSA PARA O'},
     {'codigo': 8993, 'tipo': 'TARIFA DECORRENTE DO SERVIÇO DE EMISSÃO E GERENCIAMENTO DE CERTIFI'},
     {'codigo': 9304, 'tipo': 'CIDE - COMBUSTÍVEIS - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 9303, 'tipo': 'CIDE - REMESSA EXTERIOR - LEI 10332/01 - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 8678, 'tipo': 'CIDE-COMBUSTÍVEIS - PARCELA NÃO DEDUTÍVEL'},
     {'codigo': 8707, 'tipo': 'PASEP - REGIME ESPECIAL DE PARCELAMENTO MP 38/02 E LEI 10.684/03'},
     {'codigo': 8900, 'tipo': 'RECEITA DE DÍVIDA ATIVA - ITR - EXERCÍCIOS DE 1997 E POSTERIORES'},
     {'codigo': 8504, 'tipo': 'MULTA ISOLADA CIDE-COMBUSTÍVEIS - (ART.43 LEI 9430/96)'},
     {'codigo': 8619, 'tipo': 'JUROS ISOLADOS CIDE COMBUSTÍVEIS (ART 43 L 9430/96)'},
     {'codigo': 8651, 'tipo': 'MULTA ISOLADA CIDE REMESSA AO EXTERIOR (ART 43 L 9430/96)'},
     {'codigo': 8660, 'tipo': 'JUROS ISOLADOS CIDE REMESSA AO EXTERIOR (ART 43 L 9430/96)'},
     {'codigo': 9248, 'tipo': 'COFINS - DESISTÊNCIA DE AÇÃO JUDICIAL DE QUE TRATA O ARTIGO 11 DA'},
     {'codigo': 9250, 'tipo': 'PIS - DESISTÊNCIA DE AÇÃO JUDICIAL DE QUE TRATA O ARTIGO 11 DA MP'},
     {'codigo': 9263, 'tipo': 'PASEP - DESISTÊNCIA DE AÇÃO JUDICIAL DE QUE TRATA O ARTIGO 11 DA M'},
     {'codigo': 9207, 'tipo': 'MULTA POR FALTA/ATRASO NO RECOLHIMENTO DAS CONTRIBUIÇÕES INSTITUÍD'},
     {'codigo': 9210, 'tipo': 'IRPJ - DESISTÊNCIA DE AÇÃO JUDICIAL DE QUE TRATA O ARTIGO 11 DA MP'},
     {'codigo': 9235, 'tipo': 'CSLL - DESISTÊNCIA DE AÇÃO JUDICIAL DE QUE TRATA O ARTIGO 11 DA MP'},
     {'codigo': 9316, 'tipo': 'MULTA DE OFÍCIO - CIDE - COMBUSTÍVEIS'},
     {'codigo': 9329, 'tipo': 'JUROS LANÇAMENTO DE OFÍCIO - CIDE - COMBUSTÍVEIS'},
     {'codigo': 9283, 'tipo': 'MULTA DE OFÍCIO - CIDE - REMESSA AO EXTERIOR - LEI 10332/01'},
     {'codigo': 9276, 'tipo': 'JUROS LANÇAMENTO DE OFÍCIO - CIDE - REMESSA AO EXTERIOR - LEI 1033'},
     {'codigo': 8176, 'tipo': 'CIDE-DESISTÊNCIA DE AÇÃO JUDICIAL ( ART 21 DA MP 66/02 )'},
     {'codigo': 8192, 'tipo': 'CPMF-DESISTÊNCIA DE AÇÃO JUDICIAL ( ART 21 DA MP 66/02 )'},
     {'codigo': 8459, 'tipo': 'PIS-DESISTÊNCIA DE AÇÃO JUDICIAL ( ART 21 DA MP 66/02 )'},
     {'codigo': 9073, 'tipo': 'COFINS-DESISTÊNCIA DE AÇÃO JUDICIAL ( ART 21 DA MP 66/02 )'},
     {'codigo': 9139, 'tipo': 'CONTRIBUIÇÃO SOBRE PRÊMIOS PRESCRITOS DE LOTERIAS FEDERAIS'},
     {'codigo': 9141, 'tipo': 'CONTRIBUIÇÃO SOBRE A RECEITA DE LOTERIA INSTANTÂNEA'},
     {'codigo': 9154, 'tipo': 'CONTRIBUIÇÃO SOBRE A RECEITA DE LOTERIAS DE NÚMEROS'},
     {'codigo': 9167, 'tipo': 'CONTRIBUIÇÃO SOBRE A RECEITA DE CONCURSOS ESPECIAIS DE LOTERIAS ES'},
     {'codigo': 9170, 'tipo': 'CONTRIBUIÇÃO SOBRE A RECEITA DE LOTERIAS ESPORTIVAS'},
     {'codigo': 9182, 'tipo': 'CONTRIBUIÇÃO SOBRE A RECEITA DA LOTERIA FEDERAL'},
     {'codigo': 8019, 'tipo': 'CUSTAS DA JUSTIÇA DO TRABALHO - LEI 10.537/2002'},
     {'codigo': 8168, 'tipo': 'EMOLUMENTOS DA JUSTIÇA DO TRABALHO - LEI 10.537/2002'},
     {'codigo': 7659, 'tipo': 'PARCELAMENTO - SIMPLES FEDERAL'},
     {'codigo': 7739, 'tipo': 'R D ATIVA - PARCELAMENTO DE ARREMATAÇÃO'},
     {'codigo': 7780, 'tipo': 'MULTA ISOLADA CONDECINE (ART.43 DA LEI 9.430)'},
     {'codigo': 6875, 'tipo': 'PNEUS E CÂMARAS-DE-AR DE BORRACHA ADQUIRIDOS DE FABRICANTE OU DE I'},
     {'codigo': 7384, 'tipo': 'COTA-PARTE DA CONTRIBUIÇÃO SINDICAL - DESVINCULAÇÃO DE RECEITAS DA'},
     {'codigo': 8863, 'tipo': 'BENS OU SERVIÇOS ADQUIRIDOS DE SOCIEDADES COOPERATIVAS E ASSOCIAÇÕ'},
     {'codigo': 6840, 'tipo': 'COFINS - COMBUSTÍVEIS'}, {'codigo': 7878, 'tipo': 'CONDECINE - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 7940, 'tipo': 'JUROS ISOLADOS CONDECINE (ART.43 DA LEI 9.430)'},
     {'codigo': 6883, 'tipo': 'MÁQUINAS, TRATORES, VEÍCULOS PARA TRANSPORTE DE PASSAGEIROS, DE ME'},
     {'codigo': 9060, 'tipo': 'QUEROSENE DE AVIAÇÃO ADQUIRIDO DE PRODUTOR OU IMPORTADOR - RETIDO'},
     {'codigo': 6824, 'tipo': 'PIS - COMBUSTÍVEIS'},
     {'codigo': 6939, 'tipo': 'MULTA DE OFÍCIO - IPI NÃO LANÇADO COM COBERTURA DE CRÉDITO'},
     {'codigo': 7042, 'tipo': 'PARCELAMENTO LEI 10.684/03 - PESSOA FÍSICA'},
     {'codigo': 7093, 'tipo': 'PARCELAMENTO LEI 10.684/03 - MICROEMPRESA'},
     {'codigo': 7114, 'tipo': 'PARCELAMENTO LEI 10.684/03- EMPRESA PEQ. PORTE'},
     {'codigo': 7122, 'tipo': 'PARCELAMENTO LEI 10.684/03 - DEMAIS PESSOAS JURÍDICAS'},
     {'codigo': 7376, 'tipo': 'RD ATIVA - PASEP - REGIME ESPECIAL DE PARCELAMENTO - LEI 10.684/03'},
     {'codigo': 7317, 'tipo': 'RD ATIVA - ITR - PARCELAMENTO LEI 10.684/03'},
     {'codigo': 7368, 'tipo': 'R D ATIVA - MULTA POR VIOLAÇÃO AO CÓDIGO DE DEFESA DO CONSUMIDOR'},
     {'codigo': 6744, 'tipo': 'MULTA ATRASO ENTREGA DECLARAÇÃO DE OPERAÇÕES IMOBILIÁRIAS - DOI'},
     {'codigo': 6082, 'tipo': 'R D ATIVA - CIDE REMESSAS AO EXTERIOR'},
     {'codigo': 5987, 'tipo': 'CSLL - RETENÇÃO PAGAMENTOS DE PJ A PJ DIREITO PRIVADO'},
     {'codigo': 5493, 'tipo': 'CPSSS - CONTRIBUIÇÃO PATRONAL PENSIONISTA CIVIL'},
     {'codigo': 5485, 'tipo': 'CPSSS - CONTRIBUIÇÃO PATRONAL SERVIDOR CIVIL INATIVO'},
     {'codigo': 4562, 'tipo': 'PIS - IMPORTAÇÃO DE PRODUTOS - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 6808, 'tipo': 'MULTA POR OMISSÃO/ERRO/ATRASO DACON'},
     {'codigo': 5110, 'tipo': 'IPI - CHARUTO, CIGARRILHAS E CIGARROS, NÃO CONTENDO TABACO'},
     {'codigo': 7130, 'tipo': 'MULTA ATRASO ENTREGA DECLARAÇÃO - ESPÓLIO'},
     {'codigo': 6023, 'tipo': 'R D ATIVA - CIDE COMBUSTÍVEIS'},
     {'codigo': 6656, 'tipo': 'PIS - NÃO CUMULATIVO - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 5530, 'tipo': 'CPSSS - CONTRIBUIÇÃO DO PENSIONISTA CIVIL'},
     {'codigo': 4480, 'tipo': 'RECEITA DÍVIDA ATIVA -MULTA INFRAÇÃO CÓDIGO BRASILEIRO AERONÁUTICA'},
     {'codigo': 4263, 'tipo': 'RECEITA DÍVIDA ATIVA - RESSARCIMENTOS AO FUNDO NACIONAL DE SAÚDE'},
     {'codigo': 6680, 'tipo': 'MULTA POR OMISSÃO/ERRO/ATRASO - DIMOB'},
     {'codigo': 4112, 'tipo': 'IRPJ - REGIME ESPECIAL DE TRIBUTAÇÃO DO PATRIMÔNIO DE AFETAÇÃO'},
     {'codigo': 5557, 'tipo': 'IRRF - GANHOS LÍQUIDOS EM OPERAÇÕES EM BOLSAS E ASSEMELHADOS'},
     {'codigo': 4085, 'tipo': 'RET CONTRIB PAGT EST/DF/MUNIC - BENS/SERVIÇOS - CSLL/COFINS/PIS'},
     {'codigo': 4407, 'tipo': 'COFINS - RET FONTE PAGT ESTADOS/DF/MUNICÍPIOS - BENS/SERVIÇOS'},
     {'codigo': 4397, 'tipo': 'CSLL - RET FONTE PAGT ESTADOS/DF/MUNICÍPIOS - BENS/SERVIÇOS'},
     {'codigo': 4409, 'tipo': 'PIS - RET FONTE PAGT ESTADOS/DF/MUNICÍPIOS - BENS/SERVIÇOS'},
     {'codigo': 4437, 'tipo': 'CONTRIBUIÇÃO PROGNÓSTICO ESPORTIVO - DIR PRESCRIT ENTID DESPORTIVA'},
     {'codigo': 3877, 'tipo': 'CSLL - PGT A PJ FORN INSUMO/TRANSP CARGA GERA DIR CRÉD PRESUMIDO'},
     {'codigo': 3842, 'tipo': 'IRRF - PGT A PJ FORN INSUMO/TRANSP CARGA GERA DIR CRÉD PRESUMIDO'},
     {'codigo': 3375, 'tipo': 'IRPJ - RET FONTE PAG E PÚBL, SOC EC MISTA A PJ DIR PRIV - L OFÍCIO'},
     {'codigo': 3359, 'tipo': 'PIS - RETENÇÃO FONTE PAGT PJ A PJ DIR PRIVADO - LANÇAMENTO OFÍCIO'},
     {'codigo': 3308, 'tipo': 'CSLL - RET FONTE PAGT E PÚB, SOC EC MISTA A PJ D PRIV - L OFÍCIO'},
     {'codigo': 3360, 'tipo': 'PIS - RET FONTE PAGT E PÚBL, SOC EC MISTA A PJ DIR PRIV - L OFÍCIO'},
     {'codigo': 5565, 'tipo': 'IRRF - BENEFÍCIO PREVIDÊNCIA COMPLEMENTAR/OPTANTE TRIB EXCLUSIVA'},
     {'codigo': 6904, 'tipo': 'IRRF - RENDIMENTOS DE INDENIZAÇÃO POR DANOS MORAIS'},
     {'codigo': 3682, 'tipo': 'MULTA ISOLADA - CONTRIB SOCIAIS RET FONTE - CSRF (ART. 43 L.9430)'},
     {'codigo': 3711, 'tipo': 'JUROS ISOLADOS - CONTR SOCIAIS RET FONTE - CSRF (ART. 43 L.9430)'},
     {'codigo': 3495, 'tipo': 'JUROS ISOLADOS - CONT SOC E IR RET FONTE - CSIRF (ART. 43 L.9430)'},
     {'codigo': 7229, 'tipo': 'RECEITA DÍVIDA ATIVA - TAXA FISCALIZAÇÃO MERCADOS SEGURO, CAPITALI'},
     {'codigo': 7288, 'tipo': 'ITR - PARCELAMENTO LEI 10.684/03 EX 1997 E POSTERIORES'},
     {'codigo': 5928, 'tipo': 'IRRF -REND DECOR DECISÃO JUSTIÇA FEDERAL, EXCETO ART 12A L 7713/88'},
     {'codigo': 4095, 'tipo': 'REGIME ESPECIAL DE TRIBUTAÇÃO DO PATRIMÔNIO DE AFETAÇÃO'},
     {'codigo': 4153, 'tipo': 'CSLL - REGIME ESPECIAL DE TRIBUTAÇÃO DO PATRIMÔNIO DE AFETAÇÃO'},
     {'codigo': 4138, 'tipo': 'PIS - REGIME ESPECIAL TRIBUTAÇÃO DO PATRIMÔNIO DE AFETAÇÃO'},
     {'codigo': 4166, 'tipo': 'COFINS - REGIME ESPECIAL DE TRIBUTAÇÃO DO PATRIMÔNIO DE AFETAÇÃO'},
     {'codigo': 3850, 'tipo': 'IRRF - PGT A PF FORN INSUMO/TRANSP CARGA GERA DIR CRÉD PRESUMIDO'},
     {'codigo': 6891, 'tipo': 'IRRF - VIDA GERADOR DE BENEFICIO LIVRE - VGBL'},
     {'codigo': 3482, 'tipo': 'MULTA ISOLADA - CONTR SOC E IR RET FONTE - CSIRF (ART. 43 L.9430)'},
     {'codigo': 2300, 'tipo': 'CONTRIBUIÇÃO EMPRESA/EMPREGADOR - DEPÓSITO JUDICIAL'},
     {'codigo': 5944, 'tipo': 'IRRF - PAGAMENTO DE PJ A PJ POR SERVIÇOS DE FACTORING'},
     {'codigo': 8835, 'tipo': 'TRANSPORTE INTERNACIONAL CARGA-RET ORGAO PUBL'},
     {'codigo': 8848, 'tipo': 'CONSTRUCAO/REPARO EMBARCACOES-RET ORGAO PUBL'},
     {'codigo': 8726, 'tipo': 'ALCOOL CARB ADQUIR DISTRIBUIDOR-RET ORGAO PUB'},
     {'codigo': 8739, 'tipo': 'GASOL/DIESEL/GLP E ALCOOL NO VAREJO-R ORG PUB'},
     {'codigo': 8770, 'tipo': 'DEMAIS COMBUST DERIVADOS PETR/GAS NAT-R O PUB'},
     {'codigo': 8767, 'tipo': 'MEDICAMENTO ADQUIR DISTRIB/VAREJ-RET ORG PUBL'},
     {'codigo': 8754, 'tipo': 'MEDICAMENTO ADQUIR INDUST/IMPORT-RET ORG PUBL'},
     {'codigo': 8850, 'tipo': 'TRANSPORTE INTERNACIONAL PASSAGEIRO-R ORG PUB'},
     {'codigo': 5450, 'tipo': 'FUNDAF - CÓPIAS XEROX - PGFN'},
     {'codigo': 3260, 'tipo': 'CSLL - RETENÇÃO FONTE PAGT PJ A PJ DIR PRIV - LANÇAMENTO OFÍCIO'},
     {'codigo': 3332, 'tipo': 'COFINS - RET FONTE PAGT E PÚB, SOC EC MISTA A PJ D PRIV - L OFÍCIO'},
     {'codigo': 3316, 'tipo': 'COFINS - RETENÇÃO FONTE PAGT PJ A PJ DIR PRIV - LANÇAMENTO OFÍCIO'},
     {'codigo': 958, 'tipo': 'PAGAMENTO/PARCELAMENTO - ART. 3º MP 449/08'},
     {'codigo': 6120, 'tipo': 'FINSOCIAL - DEMAIS EMPRESAS'}, {'codigo': 1458, 'tipo': 'IOF - APLICAÇÕES FINANCEIRAS'},
     {'codigo': 5042, 'tipo': 'IPI - DEVOLUÇÃO DE CRÉDITO NEGATIVO'}, {'codigo': 1759, 'tipo': 'FINSOCIAL - SERVIÇOS'},
     {'codigo': 4465, 'tipo': 'IOF - RESG INF 15D ART3 D 1031/93'},
     {'codigo': 3746, 'tipo': 'COFINS - RET FONTE - AQUISIÇÃO DE AUTOPEÇAS'},
     {'codigo': 1840, 'tipo': 'COFINS – VENDAS À ZFM – SUBSTITUIÇÃO TRIBUTÁRIA'},
     {'codigo': 1921, 'tipo': 'PIS – VENDAS À ZFM – SUBSTITUIÇÃO TRIBUTÁRIA'},
     {'codigo': 879, 'tipo': 'R D ATIVA – MULTA ISOLADA - CSIRF(ART. 43 DA LEI Nº 9.430 DE 1996)'},
     {'codigo': 1539, 'tipo': 'R D ATIVA - GASOL/DIESEL/GLP E ALCOOL VAREJO – RET ÓRGÃO PÚBLICO'},
     {'codigo': 1460, 'tipo': 'R D ATIVA - ÁLCOOL CARB ADQUIR DISTRIBUIDOR – RETIDO ÓRGÃO PUBLICO'},
     {'codigo': 1230, 'tipo': 'R D ATIVA - QUEROSENE AVIACAO ADQUIR PRODUTOR/IMP - RET ÓRGÃO PUBL'},
     {'codigo': 1214, 'tipo': 'R D ATIVA – MAQ/TRAT/VEIC TRANSP PASSAG/MERC–RETIDO ÓRGÃO PUBLICO'},
     {'codigo': 1174, 'tipo': 'R D ATIVA – PNEU/CAM-DE-AR BORR ADQUIR FABR/IMP - RETIDO ORG PUBL'},
     {'codigo': 1118, 'tipo': 'R D ATIVA - MEDICAMENTOS ADQUIR DISTRIB/VAREJ - RET ORGÃO PUBLICO'},
     {'codigo': 1065, 'tipo': 'R D ATIVA – PRODUTOS-RETIDO POR ÓRGÃO PÚBLICO'},
     {'codigo': 992, 'tipo': 'R D ATIVA – CSLL - RETENÇÃO NA FONTE'},
     {'codigo': 949, 'tipo': 'R D ATIVA - PIS - RETENÇÃO NA FONTE'},
     {'codigo': 896, 'tipo': 'R D ATIVA - COFINS - RETENÇÃO NA FONTE'},
     {'codigo': 447, 'tipo': 'PIS - IMPORTAÇÃO - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 868, 'tipo': 'PASEP - DEPÓSITO JUDICIAL'},
     {'codigo': 381, 'tipo': 'MULTA POR OMISSÃO/ERRO NA DIRF ANUAL'},
     {'codigo': 4072, 'tipo': 'FUNDAF-ATIVIDADE EXTRAORDINÁRIA DE FISCALIZ E CONTROLE ADUANEIRO'},
     {'codigo': 312, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - IRPF - NÃO TRIBUTÁRIO'},
     {'codigo': 5477, 'tipo': 'COFINS - NÃO CUMULATIVA - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 790, 'tipo': 'CONTRIB SOBRE RECEITA SORTEIO POR ENTIDADE FILANTRÓPICA - L OFÍCIO'},
     {'codigo': 860, 'tipo': 'PASEP - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 450, 'tipo': 'IRPJ - GANHO DE CAPITAL - ALIEN ATIVO ME/EPP SIMPLES- LANC OFÍCIO'},
     {'codigo': 733, 'tipo': 'IRPJ – DEVOLUÇÃO DE RECURSO APLICADOS - REDUÇÃO POR REINVESTIMENTO'},
     {'codigo': 5469, 'tipo': 'FUNDAF-DESLOCAMENTO DE SERVIDOR PRESTAR SERV FORA SEDE REPARTIÇÃO'},
     {'codigo': 6197, 'tipo': 'FUNDAF-AUDITORIA SIST INFORMAT HABILITAÇÃO REGIME ADUAN ESPECIAL'},
     {'codigo': 300, 'tipo': 'RECEITA DIREITOS ANTIDUMPING-LANÇAMENTO DE OFÍCIO'},
     {'codigo': 400, 'tipo': 'R D ATIVA - PARCELAMENTO PARA INGRESSO NO SIMPLES NACIONAL'},
     {'codigo': 75, 'tipo': 'RESSARCIMENTO CASA DA MOEDA - LEI 11.488/2007'},
     {'codigo': 231, 'tipo': 'IRPJ - GANHO LIQ OPER BOLSA - LUCRO PRES/ARBITRADO-PAG EM SEPARADO'},
     {'codigo': 4578, 'tipo': 'ENCARGOS POR RECOLHIMENTO FORA DO PRAZO - SIMPLES NACIONAL'},
     {'codigo': 163, 'tipo': 'RECEITA DIREITOS ANTIDUMPING/COMPENSATÓRIOS-DEPÓSITO JUDICIAL'},
     {'codigo': 174, 'tipo': 'RECEITA DIREITOS ANTIDUMPING/COMPENSATÓRIOS - DEPÓSITO ADM'},
     {'codigo': 176, 'tipo': 'R D ATIVA - PARCELAMENTO TIMEMANIA - CLUBES DE FUTEBOL'},
     {'codigo': 353, 'tipo': 'PARCELAMENTO TIMEMANIA'},
     {'codigo': 148, 'tipo': 'CIDE - COMBUSTÍVEIS - IMPORTAÇÃO - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 416, 'tipo': 'IRPJ-REGIME ESPECIAL TRIB-PATRIMÔNIO AFETAÇÃO-LANÇAMENTO DE OFÍCIO'},
     {'codigo': 536, 'tipo': 'R D ATIVA-PARCELAMENTO-INSTITUIÇÕES ENSINO SUPERIOR-LEI 10.260/01'},
     {'codigo': 542, 'tipo': 'CSLL-REGIME ESPECIAL TRIBUTAÇÃO-PATRIMÔNIO AFETAÇÃO-LANÇ OFÍCIO'},
     {'codigo': 3494, 'tipo': 'DOAÇÃO AO FUNDO NAC DESENVOLVIMENTO CIENTÍFICO TECNOLÓGICO - FNDCT'},
     {'codigo': 3488, 'tipo': 'MULTA POR FALTA DE RETENÇÃO NA FONTE DE IMPOSTO OU CONTRIBUIÇÃO'},
     {'codigo': 3630, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA EFD-ICMS/IPI'},
     {'codigo': 5719, 'tipo': 'IRPJ - FINOR DEVOLUÇÃO EXERCÍCIOS ANTERIORES'},
     {'codigo': 5721, 'tipo': 'IRPJ - FINAM DEVOLUÇÃO EXERCÍCIOS ANTERIORES'},
     {'codigo': 5734, 'tipo': 'IRPJ - INCENTIVOS RELATIVOS A EXERCÍCIOS ANTERIORES'},
     {'codigo': 5747, 'tipo': 'RECEITA CADASTRO ELEITORAL - TSE'},
     {'codigo': 5762, 'tipo': 'CUSTAS JUSTIÇA FEDERAL - 1 GRAU'},
     {'codigo': 5775, 'tipo': 'CUSTAS JUSTIÇA FEDERAL - 2 GRAU'},
     {'codigo': 5784, 'tipo': 'RESTITUIÇÕES - AVISO MF 087/85'},
     {'codigo': 8673, 'tipo': 'IRRF - BINGOS (DECRETO 3659/2000, ART 14,I )'},
     {'codigo': 8713, 'tipo': 'TAXA DE FISCALIZAÇÃO DE VIGIL. SANITÁRIA NOS PORTOS, AEROPORTOS E FRONTEIRAS'},
     {'codigo': 5788, 'tipo': 'IRPJ - SUPLEMENTAR'}, {'codigo': 5802, 'tipo': 'CSLL - SUPLEMENTAR'},
     {'codigo': 5843, 'tipo': 'OUTRAS CONTRIBUIÇÕES MIN. MAR. - FEF'},
     {'codigo': 9086, 'tipo': 'IRPJ - GANHOS LÍQ OPER BOLSA INVEST PAÍS C/ TRIBUTAÇÃO FAVORECIDA'},
     {'codigo': 5864, 'tipo': 'TRANSFERENCIAS DE INSTITUIÇÕES PRIVADAS - OUTROS'},
     {'codigo': 5869, 'tipo': 'CPMF - LANÇAMENTO DÉBITO EM CONTA'},
     {'codigo': 5871, 'tipo': 'CPMF-OPER. LIQUIDAÇÃO/PAGAMENTO VALORES NÃO CREDITADOS EM CONTA DO BENEFICIÁRIO'},
     {'codigo': 5872, 'tipo': 'TRANSFERENCIAS DO EXTERIOR - OUTROS'},
     {'codigo': 5880, 'tipo': 'TRANSFERENCIAS DE PESSOAS - OUTROS'},
     {'codigo': 5884, 'tipo': 'CPMF - INSTITUIÇÃO FINANCEIRA COMO CONTRIBUINTE'},
     {'codigo': 5897, 'tipo': 'PARCELAMENTO PESSOA FÍSICA - SIMPLES'},
     {'codigo': 5909, 'tipo': 'PARCELAMENTO PESSOA JURÍDICA - SIMPLES'},
     {'codigo': 5911, 'tipo': 'RECEITA DÍVIDA ATIVA - AVALES E FIANÇAS - INSTITUTO DO AÇÚCAR E DO ÁLCOOL'},
     {'codigo': 5937, 'tipo': 'MULTA REGULAMENTAR CSLL SUPLEMENTAR'},
     {'codigo': 5940, 'tipo': 'MULTA REGULAMENTAR IRPJ SUPLEMENTAR'},
     {'codigo': 5965, 'tipo': 'RECEITA DÍVIDA ATIVA - CONVERSÃO DEPOSITO JUDICIAL/ EXECUÇÃO FISCAL/ EMBARGOS'},
     {'codigo': 5978, 'tipo': 'RECEITA DÍVIDA ATIVA - CPMF'},
     {'codigo': 5980, 'tipo': 'CPMF - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 6000, 'tipo': 'IPI - RESSARCIMENTO (CONTROLE SRF)'},
     {'codigo': 6015, 'tipo': 'IRPF - GANHOS LÍQUIDOS EM OPERAÇÕES EM BOLSA'},
     {'codigo': 6079, 'tipo': 'MULTA CONTRATUAL BEFIEX (S/REDUÇÃO)'},
     {'codigo': 6081, 'tipo': 'ITR - CONVERSÃO DEPÓSITO JUDICIAL'},
     {'codigo': 6090, 'tipo': 'SERVIÇOS PROCESSAMENTO DE DADOS - FUNDAF'},
     {'codigo': 6094, 'tipo': 'MULTA ISOLADA - CSLL (ART. 43 L.9430)'},
     {'codigo': 6106, 'tipo': 'PAGAMENTO DE MICROEMPRESA E EMPRESA DE PEQUENO PORTE - SIMPLES'},
     {'codigo': 6147, 'tipo': 'PRODUTOS - RETENÇÃO EM PAGAMENTOS POR ÓRGÃO PÚBLICO'},
     {'codigo': 6150, 'tipo': 'COMBUSTÍVEL - RETENÇÃO EM PAGAMENTO POR ÓRGÃO PÚBLICO'},
     {'codigo': 6175, 'tipo': 'TRANSPORTE DE PASSAGEIROS - RETENÇÃO EM PAGAMENTO POR ÓRGÃO PÚBLICO'},
     {'codigo': 6188, 'tipo': 'FINANCEIRAS - RETENÇÃO EM PAGAMENTO POR ÓRGÃO PÚBLICO'},
     {'codigo': 6190, 'tipo': 'SERVIÇOS - RETENÇÃO EM PAGAMENTO POR ÓRGÃO PÚBLICO'},
     {'codigo': 6215, 'tipo': 'ENTIDADES ISENTAS - RETENÇÃO EM PAGAMENTO POR ÓRGÃO PÚBLICO'},
     {'codigo': 6228, 'tipo': 'CSLL - RETENÇÃO NA FONTE SOBRE PAGAMENTO DE ÓRGÃO PUBLICO A PESSOA JURÍDICA'},
     {'codigo': 6230, 'tipo': 'PIS-RETENÇÃO NA FONTE SOBRE PAGAMENTO EFETUADO POR ÓRG PUBLICO A PESSOA JURÍDICA'},
     {'codigo': 6243, 'tipo': 'COFINS - RETENÇÃO NA FONTE - PAGAMENTO DE ÓRGÃO PÚBLICO A PESSOA JURÍDICA'},
     {'codigo': 6250, 'tipo': 'RECEITA DE LEILÕES MERCADORIAS APREENDIDAS'},
     {'codigo': 6256, 'tipo': 'IRPJ - PAGAMENTO EFETUADO POR ÓRGÃO PÚBLICO'},
     {'codigo': 6297, 'tipo': 'IRPJ-GANHOS DE CAPITAL NA ALIEN. DE ATIVOS–MICROEMPRESA/EPP OPTANTE PELO SIMPLES'},
     {'codigo': 6311, 'tipo': 'RECEITA DÍVIDA ATIVA - AMORTIZAÇÃO JUROS EMPRÉSTIMO AO FUNDO DE MARINHA MERCANTE'},
     {'codigo': 6324, 'tipo': 'MULTA ISOLADA - PIS/PASEP (ART. 43 L.9430)'},
     {'codigo': 6337, 'tipo': 'MULTA ISOLADA - COFINS (ART. 43 L.9430)'},
     {'codigo': 6340, 'tipo': 'MULTA ISOLADA - IMP. IMPORTAÇÃO (ART. 43 L.9430)'},
     {'codigo': 6352, 'tipo': 'MULTA ISOLADA - IRPF (ART. 43 L.9430)'},
     {'codigo': 6378, 'tipo': 'MULTA ISOLADA - IRPJ (ART. 43 L.9430)'},
     {'codigo': 6380, 'tipo': 'MULTA ISOLADA - IRRF (ART. 43 L.9430)'},
     {'codigo': 6393, 'tipo': 'MULTA ISOLADA - IPI VINCULADO (ART. 43 L.9430)'},
     {'codigo': 6402, 'tipo': 'MULTA DO TCU'}, {'codigo': 6405, 'tipo': 'MULTA ISOLADA - IPI (ART. 43 L.9430)'},
     {'codigo': 6410, 'tipo': 'FUNDAF - SELOS ESPECIAIS DE CONTROLE - OUTROS'},
     {'codigo': 6418, 'tipo': 'MULTA ISOLADA - IOF (ART. 43 L.9430)'},
     {'codigo': 6420, 'tipo': 'MULTA ISOLADA - CPMF (ART. 43 L.9430)'},
     {'codigo': 6470, 'tipo': 'SERVIÇOS TECNOLÓGICOS - FNS'},
     {'codigo': 6488, 'tipo': 'SERVIÇOS DE LABORATÓRIO DE ANALISES - SRF'},
     {'codigo': 6525, 'tipo': 'FUNDAF - RESSARCIMENTO RECEITAS DE RECINTOS ALFANDEGADOS'},
     {'codigo': 6542, 'tipo': 'JUROS IMPOSTO IMPORTAÇÃO - (ART. 43 L.9430)'},
     {'codigo': 6555, 'tipo': 'JUROS IRPF - (ART. 43 L.9430)'},
     {'codigo': 6570, 'tipo': 'JUROS IRPJ - (ART. 43 L.9430)'},
     {'codigo': 6583, 'tipo': 'JUROS IRRF - (ART. 43 L.9430)'},
     {'codigo': 6596, 'tipo': 'JUROS IPI - (ART. 43 L.9430)'},
     {'codigo': 6608, 'tipo': 'JUROS IPI - VINCULADO (ART. 43 L.9430)'},
     {'codigo': 6610, 'tipo': 'JUROS IOF - (ART. 43 L.9430)'},
     {'codigo': 6623, 'tipo': 'JUROS COFINS (ART. 43 L.9430)'},
     {'codigo': 6630, 'tipo': 'MULTAS PREVISTAS NA LEGISLAÇÃO DO REGISTRO DE COMERCIO'},
     {'codigo': 6636, 'tipo': 'JUROS PIS/PASEP - (ART. 43 L.9430)'},
     {'codigo': 6649, 'tipo': 'JUROS CSLL - (ART. 43 L.9430)'}, {'codigo': 6651, 'tipo': 'JUROS CPMF (ART. 43 L.9430)'},
     {'codigo': 6677, 'tipo': 'IRPJ - FINOR - ESTIMATIVA'}, {'codigo': 6692, 'tipo': 'IRPJ - FINAM - ESTIMATIVA'},
     {'codigo': 6704, 'tipo': 'IRPJ - FUNRES - ESTIMATIVA'},
     {'codigo': 6720, 'tipo': 'RECEITA OUTORGA SERVIÇOS DE TRANSPORTE FERROVIÁRIO'},
     {'codigo': 6732, 'tipo': 'CONTRIBUIÇÃO SOBRE A RECEITA DE CONCURSOS DE PROGNÓSTICOS - CRÉDITO EDUCATIVO'},
     {'codigo': 6758, 'tipo': 'CSLL - ENTIDADES FINANCEIRAS - DECLARAÇÃO DE AJUSTE'},
     {'codigo': 6773, 'tipo': 'CSLL - DEMAIS PESSOAS JURÍDICAS - DECLARAÇÃO DE AJUSTE'},
     {'codigo': 6786, 'tipo': 'SUPERÁVIT FINANCEIRO EXERCÍCIOS ANTERIORES'},
     {'codigo': 6799, 'tipo': 'IRRF - RESGATE DE FUNDO DE APOSENTADORIA PROGRAMADA INDIVIDUAL - FAPI'},
     {'codigo': 6800, 'tipo': 'IRRF - APLICAÇÕES FINANCEIRAS EM FUNDOS DE INVESTIMENTO DE RENDA FIXA'},
     {'codigo': 6813, 'tipo': 'IRRF - FUNDOS DE INVESTIMENTO - AÇÕES'},
     {'codigo': 6841, 'tipo': 'MULTA POR FALTA DE COMUNICAÇÃO DA EXCLUSÃO DO SIMPLES NACIONAL'},
     {'codigo': 6854, 'tipo': 'IOF - TÍTULOS OU VALORES MOBILIÁRIOS'},
     {'codigo': 6882, 'tipo': 'MULTA FALTA PLACA SIMPLES (C/RED)'},
     {'codigo': 6895, 'tipo': 'IOF - FACTORING (ART. 58 LEI 9532/97)'},
     {'codigo': 6907, 'tipo': 'MULTA EMPRESAS INATIVAS (PARCELAMENTO)'},
     {'codigo': 6910, 'tipo': 'DIVIDENDOS - OUTRAS EMPRESAS'},
     {'codigo': 6922, 'tipo': 'TAXA AUTORIZAÇÃO TRABALHO ESTRANGEIRO'},
     {'codigo': 6935, 'tipo': 'INDENIZAÇÃO ITAIPÚ - PARCELAS VENCIDAS ATÉ JUL/97'},
     {'codigo': 6948, 'tipo': 'RECEITA DÍVIDA ATIVA - CRÉDITOS CONTRATUAIS DA UNIÃO - STN'},
     {'codigo': 7010, 'tipo': 'OUTRAS RECEITAS ATIVIDADES ASSOCIADAS À OUTORGA DE SERVIÇOS TRANSP. FERROVIÁRIO'},
     {'codigo': 7023, 'tipo': 'RECEITA DÍVIDA ATIVA - ÓRGÃO EXTINTOS, OUTRAS OBRIGAÇÕES SALVO IAA E FINEX/PROEX'},
     {'codigo': 7034, 'tipo': 'ENCARGO LEGAL DO DECRETO-LEI Nº 1.025/69 - PGFN (AJUIZADO)'},
     {'codigo': 7036, 'tipo': 'JUROS ITR - (ART. 43 L.9430)'},
     {'codigo': 7049, 'tipo': 'MULTA ISOLADA - ITR (ART. 43 L.9430)'},
     {'codigo': 6950, 'tipo': 'RECEITA DIVIDA ATIVA- CONTRATO COMISSÃO COORD CRIAÇÃO CAVALO NACIONAL(L.7291/84)'},
     {'codigo': 7051, 'tipo': 'ITR - LANÇAMENTO DE OFÍCIO'}, {'codigo': 7064, 'tipo': 'RECEITA DÍVIDA ATIVA - FUNAPOL'},
     {'codigo': 7080, 'tipo': 'PAGAMENTO PELA RETENÇÃO DE ÁREA PARA EXPLORAÇÃO OU PRODUÇÃO'},
     {'codigo': 7092, 'tipo': 'JUROS CPSSS (ART. 43 L. 9430)'}, {'codigo': 7104, 'tipo': 'IRPJ - SIMPLES'},
     {'codigo': 7117, 'tipo': 'MULTA ISOLADA-CONTRIB AO PLANO DE SEGURIDADE SOC DO SERVIDOR (ART. 43, LEI 9430)'},
     {'codigo': 7120, 'tipo': 'CPSSS - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 7160, 'tipo': 'RECEITA OUTORGA SERVIÇO TRANSPORTE RODOVIÁRIO'},
     {'codigo': 7186, 'tipo': 'MULTAS OPERAÇÃO DO TRANSPORTE RODOVIÁRIO'},
     {'codigo': 7199, 'tipo': 'BÔNUS DE ASSINATURA DE CONTRATO DE CONCESSÃO'},
     {'codigo': 7200, 'tipo': 'PIS - SIMPLES'}, {'codigo': 7202, 'tipo': 'CAUÇÕES E GARANTIAS DIVERSAS'},
     {'codigo': 7213, 'tipo': 'CPMF - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 7254, 'tipo': 'ROYALTIES 5% (E-M) (L 7990 ART. 7 I A III)'},
     {'codigo': 7267, 'tipo': 'ROYALTIES 5% (E-M) (L 7990 ART. 7 P 4)'},
     {'codigo': 7282, 'tipo': 'ROYALTIES EXCEDENTES A 5% (E/M) LEI 9.478, ART. 49, I'},
     {'codigo': 7295, 'tipo': 'ROYALTIES EXCEDENTES A 5% (MCT) LEI 9.478, ART. 49 , I'},
     {'codigo': 7307, 'tipo': 'CSLL - SIMPLES'}, {'codigo': 7309, 'tipo': 'DEPÓSITOS (MULTAS CLT)'},
     {'codigo': 7310, 'tipo': 'ROYALTIES EXCEDENTES A 5% (E-M) LEI 9.478, ART. 49,II'},
     {'codigo': 7322, 'tipo': 'ROYALTIES EXCEDENTES A 5% (MM/MCT) LEI 9.478, ART. 49, II'},
     {'codigo': 7335, 'tipo': 'PARTICIPAÇÃO ESPECIAL (E-M) (L 9478 ART. 50)'},
     {'codigo': 7348, 'tipo': 'PARTICIPAÇÃO ESPECIAL (MME/MMA) LEI 9.478, ART. 50'},
     {'codigo': 7363, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - DEPÓSITO JUDICIAL'},
     {'codigo': 7389, 'tipo': 'IPI - OUTROS DEPÓSITO JUDICIAL'},
     {'codigo': 7391, 'tipo': 'IPI - VINCULADO IMPORTAÇÃO DEPÓSITO JUDICIAL'},
     {'codigo': 7403, 'tipo': 'COFINS - SIMPLES'}, {'codigo': 7405, 'tipo': 'DEPÓSITOS ABANDONADOS'},
     {'codigo': 7416, 'tipo': 'IRPF - DEPÓSITO JUDICIAL'}, {'codigo': 7429, 'tipo': 'IRPJ - DEPÓSITO JUDICIAL'},
     {'codigo': 7431, 'tipo': 'IRRF - DEPÓSITO JUDICIAL'}, {'codigo': 7444, 'tipo': 'IOF - DEPÓSITO JUDICIAL'},
     {'codigo': 7457, 'tipo': 'ITR - DEPÓSITO JUDICIAL'}, {'codigo': 7460, 'tipo': 'PIS - DEPÓSITO JUDICIAL'},
     {'codigo': 7485, 'tipo': 'CSLL - DEPÓSITO JUDICIAL'}, {'codigo': 7498, 'tipo': 'COFINS - DEPÓSITO JUDICIAL'},
     {'codigo': 7500, 'tipo': 'INSS- CONTRIBUIÇÃO DO EMPREGADOR - SIMPLES'},
     {'codigo': 7501, 'tipo': 'DEPÓSITOS PARA QUEM DE DIREITO'}, {'codigo': 7512, 'tipo': 'CPMF - DEPÓSITO JUDICIAL'},
     {'codigo': 7525, 'tipo': 'R D ATIVA - DEP. GARANTIA JUIZO/JUST. FED.'},
     {'codigo': 7538, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7540, 'tipo': 'IPI - OUTROS DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7553, 'tipo': 'IPI - VINCULADO IMPORTAÇÃO DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7566, 'tipo': 'IRPF - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7581, 'tipo': 'IRPJ - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7594, 'tipo': 'IRRF - DEPOSITO ADMINISTRATIVO'}, {'codigo': 7606, 'tipo': 'IPI - SIMPLES'},
     {'codigo': 7616, 'tipo': 'RECEITA DIVIDA ATIVA - EMPRÉSTIMO COMPULSÓRIO PRINCIPAL'},
     {'codigo': 7619, 'tipo': 'IOF - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7621, 'tipo': 'ITR - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7634, 'tipo': 'PIS - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7647, 'tipo': 'CSLL - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7650, 'tipo': 'COFINS - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7662, 'tipo': 'CPMF - DEPÓSITO ADMINISTRATIVO'}, {'codigo': 7702, 'tipo': 'ICMS - SIMPLES'},
     {'codigo': 7704, 'tipo': 'TRANSFERENCIAS DA UNIÃO'},
     {'codigo': 7715, 'tipo': 'RENDA LIQUÍDA LOTERIA ESPORTIVA FEDERAL - APAES - DEC 2843/98'},
     {'codigo': 7728, 'tipo': 'RECEITA EM CONSIGNAÇÃO PAGAMENTO DE SERVIÇOS PÚBLICOS ( ART. 12, DEC. 2.784/98)'},
     {'codigo': 7730, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - TRANS NAVIOS'},
     {'codigo': 7743, 'tipo': 'IPI - VINCULADO IMPORTAÇÃO TRANS NAVIOS'},
     {'codigo': 7756, 'tipo': 'IRPJ - TRANS NAVIOS'},
     {'codigo': 7769, 'tipo': 'IRRF - DEMAIS RENDIMENTOS TRANS NAVIOS'},
     {'codigo': 7784, 'tipo': 'COFINS - TRANS NAVIOS'}, {'codigo': 7797, 'tipo': 'PIS - TRANS NAVIOS'},
     {'codigo': 7809, 'tipo': 'ISS - SIMPLES'}, {'codigo': 7837, 'tipo': 'CSLL - TRANS NAVIOS'},
     {'codigo': 7840, 'tipo': 'JUROS SOBRE CAPITAL PRÓPRIO'},
     {'codigo': 7852, 'tipo': 'RECEITA ALIENAÇÃO DE AÇÕES RECEBIDAS EM PAGAMENTO DE DIVIDENDOS'},
     {'codigo': 7865, 'tipo': 'TARIFA E ADICIONAL SOBRE PASSAGEM AÉREA INTERNACIONAL (MP 1792)'},
     {'codigo': 7880, 'tipo': 'MULTAS ISOLADAS DIVERSAS - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 7893, 'tipo': 'IOF - OPERAÇÕES DE CRÉDITO - PESSOA FÍSICA'},
     {'codigo': 7905, 'tipo': 'IOF - AQUISIÇÃO DE TÍTULOS OU VALORES MOBILIÁRIOS'},
     {'codigo': 7918, 'tipo': 'RECEITA DA DÍVIDA ATIVA - MULTAS DA AGÊNCIA NACIONAL DO PETRÓLEO'},
     {'codigo': 7920, 'tipo': 'IRPJ - FINOR AJUSTE ANUAL'}, {'codigo': 7933, 'tipo': 'IRPJ - FINAM AJUSTE ANUAL'},
     {'codigo': 7946, 'tipo': 'IRPJ - FUNRES AJUSTE ANUAL'},
     {'codigo': 7959, 'tipo': 'DEPÓSITO JUDICIAL OU EXTRAJUDICIAL NÃO CLASSIFICADO'},
     {'codigo': 7961, 'tipo': 'R D ATIVA - DEP. GARANTIA JUIZO/JUST. ESTADUAL'},
     {'codigo': 7987, 'tipo': 'COFINS - ENTIDADES FINANCEIRAS E EQUIPARADAS'},
     {'codigo': 8002, 'tipo': 'PIS - DEDUÇÃO'}, {'codigo': 8021, 'tipo': 'PORTE DE REMESSA E RETORNO DOS AUTOS'},
     {'codigo': 8050, 'tipo': 'DEPÓSITO ADMINISTRATIVO - OUTROS'},
     {'codigo': 8053, 'tipo': 'IRRF - APLICAÇÕES FINANCEIRAS DE RENDA FIXA - PESSOA FÍSICA'},
     {'codigo': 8062, 'tipo': 'RECEITA DÍVIDA ATIVA - MULTAS PREVISTAS NO CÓDIGO ELEITORAL E LEIS CONEXAS'},
     {'codigo': 8102, 'tipo': 'VENDA DE PARTICIP ACIONARIA UNIAO - TELEBRAS'},
     {'codigo': 8128, 'tipo': 'MULTA ISOLADA IRPJ - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8130, 'tipo': 'MULTA ISOLADA IPI - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8143, 'tipo': 'MULTA ISOLADA PIS - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8156, 'tipo': 'MULTA ISOLADA COFINS - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8169, 'tipo': 'MULTA ISOLADA CSLL - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8171, 'tipo': 'MULTA ISOLADA INSS EMPREGADOR - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8197, 'tipo': 'MULTA ISOLADA ICMS - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8205, 'tipo': 'PIS - REPIQUE IMPOSTO DE RENDA'},
     {'codigo': 8209, 'tipo': 'MULTA ISOLADA ISS - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8211, 'tipo': 'JUROS ISOLADO IRPJ - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8224, 'tipo': 'JUROS ISOLADO IPI - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8237, 'tipo': 'JUROS ISOLADO PIS - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8240, 'tipo': 'JUROS ISOLADO COFINS- SIMPLES (ART.43 L.9430)'},
     {'codigo': 8252, 'tipo': 'JUROS ISOLADO CSLL - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8256, 'tipo': 'COTA PARTE INDENIZAÇÃO PELA EXTRAÇÃO DE PETRÓLEO, XISTO E GÁS (MM)'},
     {'codigo': 8265, 'tipo': 'JUROS ISOLADO INSS EMPREGADOR - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8278, 'tipo': 'JUROS ISOLADO ICMS - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8293, 'tipo': 'JUROS ISOLADO ISS - SIMPLES (ART.43 L.9430)'},
     {'codigo': 8301, 'tipo': 'PIS - FOLHA DE PAGAMENTO'},
     {'codigo': 8539, 'tipo': 'EMOLUMENTOS CONSULARES - EXTERIOR'},
     {'codigo': 8774, 'tipo': 'CONTRIBUIÇÃO AO FUNDO NACIONAL DA CULTURA - FUNDOS DE INVESTIMENTO REGIONAL'},
     {'codigo': 9064, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - ADICIONAL'},
     {'codigo': 9136, 'tipo': 'MULTA/JUROS DE TRANSFERÊNCIA - SPU'},
     {'codigo': 9494, 'tipo': 'OUTRAS RECEITAS - CAPITAL'},
     {'codigo': 9646, 'tipo': 'TRANSFERENCIAS DE CAPITAL - MUNICÍPIOS'},
     {'codigo': 9742, 'tipo': 'TRANSFERENCIAS DE INSTITUIÇÕES PRIVADAS'},
     {'codigo': 9953, 'tipo': 'TRANSFERENCIAS DO EXTERIOR'},
     {'codigo': 8468, 'tipo': 'IRRF - DAY-TRADE OPERAÇÕES EM BOLSA'},
     {'codigo': 9100, 'tipo': 'REFIS - PARCELAMENTO VINCULADO RECEITA BRUTA'},
     {'codigo': 9113, 'tipo': 'ITR - PARCELAMENTO ALTERNATIVO EXERCÍCIO 1996 E ANTERIORES'},
     {'codigo': 9126, 'tipo': 'ITR - PARCELAMENTO ALTERNATIVO EXERCÍCIO 1997 E POSTERIORES'},
     {'codigo': 9222, 'tipo': 'REFIS - PARCELAMENTO ALTERNATIVO'}, {'codigo': 8510, 'tipo': 'MULTA - VALE PEDÁGIO'},
     {'codigo': 8632, 'tipo': 'COMPENSAÇÃO FINANCEIRA PELA UTILIZAÇÃO DE RECURSOS HIDRICOS (ART. 28, LEI 9984/0'},
     {'codigo': 8536, 'tipo': 'CPMF - AÇÃO JUDICIAL (ARTS. 45 E 46 DA MP 2.037-21/00)'},
     {'codigo': 8549, 'tipo': 'RECEITA DE OUTORGA DE SERVIÇOS DE TELECOMUNICAÇÕES'},
     {'codigo': 8564, 'tipo': 'CPSSS - CONTRIBUIÇÃO DO MILITAR NA ATIVA'},
     {'codigo': 8577, 'tipo': 'CPSSS - CONTRIBUIÇÃO DO MILITAR NA RESERVA, REFORMADO E PENSIONISTA'},
     {'codigo': 8592, 'tipo': 'CPSSS - CONTRIBUIÇÃO DO SERVIDOR CIVIL INATIVO'},
     {'codigo': 8604, 'tipo': 'REFIS - COMPENSAÇÃO'}, {'codigo': 8620, 'tipo': 'REFIS - COMPENSAÇÃO ITR'},
     {'codigo': 8658, 'tipo': 'REFIS/SIMPLES-PARCEL/TO ESPECIAL (MP 2061/00)'},
     {'codigo': 8523, 'tipo': 'IRPF - GANHOS DE CAPITAL NA OPERAÇÃO COM MOEDA ESTRANGEIRA - IN/SRF M.02 DE 2000'},
     {'codigo': 8617, 'tipo': 'RECEITA DIRETAMENTE ARRECADADA'},
     {'codigo': 8699, 'tipo': 'CONTRIBUIÇÃO SOBRE RECEITA DE BINGOS - PARCELA DESTINADA À UNIÃO (DEC.3695/00)'},
     {'codigo': 8700, 'tipo': 'TAXA DE FISCALIZAÇÃO SANITÁRIA'},
     {'codigo': 8822, 'tipo': 'RECEITA DE DÍVIDA ATIVA - SIMPLES'},
     {'codigo': 8876, 'tipo': 'RECEITA DE DÍVIDA ATIVA - INSS SIMPLES'},
     {'codigo': 8891, 'tipo': 'RECEITA DE DÍVIDA ATIVA - ICMS SIMPLES'},
     {'codigo': 8903, 'tipo': 'RECEITA DE DÍVIDA ATIVA - ISS SIMPLES'},
     {'codigo': 8972, 'tipo': 'IRPJ - RENDIMENTO DE PROVISÕES, RESERVAS TÉCNICAS E FUNDOS DE ENTI'},
     {'codigo': 8998, 'tipo': 'IRPJ - IN SRF 89/2001,ART 7, PARÁGRAFO 8'},
     {'codigo': 9562, 'tipo': 'COFINS - IN SRF 89/2001,ART 7, PARÁGRAFO 8'},
     {'codigo': 9558, 'tipo': 'PIS - IN SRF 89/2001,ART. 7, PARÁGRAFO 8'},
     {'codigo': 9344, 'tipo': 'IRPJ - FINOR - AJUSTE ANUAL - PESSOA JURÍDICA QUE ATENDA ÀS CONDIÇ'},
     {'codigo': 9360, 'tipo': 'IRPJ - FINAM - AJUSTE ANUAL - PESSOA JURÍDICA QUE ATENDA ÀS CONDIÇ'},
     {'codigo': 9372, 'tipo': 'IRPJ - FUNRES - AJUSTE ANUAL - PESSOA JURÍDICA QUE ATENDA ÀS CONDI'},
     {'codigo': 9427, 'tipo': 'IRRF - REMUNERAÇÃO DE DIREITOS - RESIDENTES NO EXTERIOR'},
     {'codigo': 9466, 'tipo': 'IRRF - BENEFÍCIOS E RESGATE DE PREVIDÊNCIA PRIVADA E FAPI - RESIDE'},
     {'codigo': 9478, 'tipo': 'IRRF - ALUGUEL E ARRENDAMENTO - RESIDENTES NO EXTERIOR'},
     {'codigo': 2323, 'tipo': 'CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESI - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2619, 'tipo': 'CONTRIBUIÇÃO SEGURADO - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 2625, 'tipo': 'CONTRIBUIÇÃO EMPRESA/EMPREGADOR - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 3903, 'tipo': 'REABERTURA L11941/09 - RFB- DÉB PREV- PG À VISTA COM PF E BCN CSLL'},
     {'codigo': 3955, 'tipo': 'REABERTURA L 11941/2009 - RFB - APROV INDEVIDO CRÉDITO IPI - ART 2'},
     {'codigo': 4071, 'tipo': 'LEI 12865/13 - RFB -PAGAMENTO À VISTA - PIS/COFINS - ART 39, CAPUT'},
     {'codigo': 4133, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO PREVIDENCIÁRIA SEGURADOS'},
     {'codigo': 4156, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO EMPRESA/EMPREGADOR'},
     {'codigo': 4185, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO SUJEITA A RETENÇÃO PREVIDENCIÁRIA'},
     {'codigo': 4299, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESI'},
     {'codigo': 4309, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAC'},
     {'codigo': 4230, 'tipo': 'R D ATIVA- CONTRIB OUTRAS ENTIDADES/FUNDOS - FUNDO AEROVIÁRIO'},
     {'codigo': 4218, 'tipo': 'R D ATIVA - CONTRIB OUTRAS ENTIDADES/FUNDOS - SENAR'},
     {'codigo': 4344, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESCOOP'},
     {'codigo': 4350, 'tipo': 'R D ATIVA -MULTA ISOLADA COMPENSAÇÃO PREVIDENCIÁRIA INDEVIDA'},
     {'codigo': 4373, 'tipo': 'R D ATIVA -MULTA REGULAMENTAR DESCUMPRIMENTO OBRIG ACESSÓRIA PREV'},
     {'codigo': 4380, 'tipo': 'R D ATIVA - GLOSA DE COMPENSAÇÃO PREVIDENCIÁRIA'},
     {'codigo': 4162, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO RISCO AMBIENTAL/APOSENTADORIA ESPECIAL'},
     {'codigo': 4201, 'tipo': 'R D ATIVA - CONTRIB OUTRAS ENTIDADES/FUNDOS - SALÁRIO EDUCAÇÃO'},
     {'codigo': 4224, 'tipo': 'R D ATIVA - CONTRIB OUTRAS ENTIDADES/FUNDOS - INCRA'},
     {'codigo': 4282, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAI'},
     {'codigo': 4321, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SESC'},
     {'codigo': 4338, 'tipo': 'R D ATIVA - CIDE - CONTRIB OUTRA ENTIDADE/FUNDO - SEBRAE/APEX/ABDI'},
     {'codigo': 4253, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - FDEPM'},
     {'codigo': 4276, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SEST'},
     {'codigo': 4260, 'tipo': 'R D ATIVA - CONTRIBUIÇÃO OUTRAS ENTIDADES/FUNDOS - SENAT'},
     {'codigo': 4396, 'tipo': 'PARCELAMENTO DE ARREMATAÇÃO - PRIMEIRA PARCELA - DEPÓSITO JUDICIAL'},
     {'codigo': 4429, 'tipo': 'REABERTURA L 11941/09-PGFN-DÉB PREV- PARC Ñ PARC ANT-ART 1-DEP JUD'},
     {'codigo': 4435, 'tipo': 'REABERTURA L 11941/09- PGFN- DÉBITO PREVIDENCIÁRIO- ART 3- DEP JUD'},
     {'codigo': 4412, 'tipo': 'REABERTURA L 11941/09-PGFN-DEM DÉB-PARC NÃO PARC ANT-ART 1-DEP JUD'},
     {'codigo': 4487, 'tipo': 'REABERTURA L 11941/09-RFB- DÉB PREV- PARC Ñ PARC ANT-ART 1-DEP JUD'},
     {'codigo': 4510, 'tipo': 'REABERTURA L 11941/09 - RFB- DÉBITO PREVIDENCIÁRIO- ART 3- DEP JUD'},
     {'codigo': 4526, 'tipo': 'REABERTURA L 11941/09- RFB-DEM DÉB-PARC NÃO PARC ANT-ART 1-DEP JUD'},
     {'codigo': 4464, 'tipo': 'REABERTURA L 11941/09- PGFN- DEMAIS DÉBITOS- ART 3 - DEP JUDICIAL'},
     {'codigo': 4470, 'tipo': 'REABERTURA L11941/09-PGFN- APROV INDEVIDO CRÉD IPI- ART 2- DEP JUD'},
     {'codigo': 4406, 'tipo': 'MULTA POR ATRASO NA ENTREGA DO PGDAS-D'},
     {'codigo': 4698, 'tipo': 'R D ATIVA - REG ESPECIAL - PAGTO UNIFICADO -OBRA CRECHE/PRÉ-ESCOLA'},
     {'codigo': 4532, 'tipo': 'REABERTURA L 11941/09 - RFB- DEMAIS DÉBITOS- ART 3 - DEP JUDICIAL'},
     {'codigo': 4549, 'tipo': 'REABERTURA L 11941/09-RFB- APROV INDEVIDO CRÉD IPI- ART 2- DEP JUD'},
     {'codigo': 4617, 'tipo': 'L 12865/13 - RFB - PARCELAMENTO PIS/COFINS- ART 39, CAPUT- DEP JUD'},
     {'codigo': 4623, 'tipo': 'L 12865/13 - PGFN- PARCELAMENTO PIS/COFINS- ART 39, CAPUT- DEP JUD'},
     {'codigo': 4646, 'tipo': 'L 12865/13 - RFB -PARCELAMENTO PIS/COFINS - ART 39, § 1º - DEP JUD'},
     {'codigo': 4652, 'tipo': 'L 12865/13 - PGFN -PARCELAMENTO PIS/COFINS- ART 39, § 1º - DEP JUD'},
     {'codigo': 4675, 'tipo': 'LEI 12.865/2013 - RFB - PARCELAMENTO IRPJ/CSLL - ART. 40 - DEP JUD'},
     {'codigo': 4681, 'tipo': 'LEI 12.865/2013 - PGFN - PARCELAMENTO IRPJ/CSLL - ART 40 - DEP JUD'},
     {'codigo': 5370, 'tipo': 'RECEITA DÍVIDA ATIVA - CRÉDITO RURAL - STN'},
     {'codigo': 4685, 'tipo': 'COFINS - IMPORTAÇÃO DE BENS - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 2985, 'tipo': 'CONTRIB PREVID SOBRE RECEITA BRUTA - ART. 7º LEI 12.546/2011'},
     {'codigo': 3014, 'tipo': 'ROYALTIES EXCEDENTE 5% - LAVRA NA ÁREA PRÉ-SAL - EM PLATAFORMA'},
     {'codigo': 3037, 'tipo': 'PARTICIPAÇÃO ESPECIAL - LAVRA NA ÁREA PRÉ-SAL'},
     {'codigo': 3066, 'tipo': 'LEI 11.941/2009 - PGFN - DEB PREVID - PARCEL - ART. 3º - DEP JUD'},
     {'codigo': 3089, 'tipo': 'LEI 11.941/09 - PGFN-DEMAIS DÉBITOS - PARCEL - ART. 3º - DEP JUD'},
     {'codigo': 3095, 'tipo': 'LEI 11.941/09-RFB-PARCEL APROV INDEVIDO CRÉD IPI-ART. 2º- DEP JUD'},
     {'codigo': 3111, 'tipo': 'LEI 11.941/09 - RFB - DEB PREVIDENC - PARCEL - ART.3º - DEP JUD'},
     {'codigo': 3128, 'tipo': 'LEI 11.941/09 - RFB - DEMAIS DÉBITOS - PARCEL - ART. 3º- DEP JUD'},
     {'codigo': 3134, 'tipo': 'R D ATIVA - IRPJ - LANÇADO DE OFÍCIO - SIMPLES NACIONAL'},
     {'codigo': 3157, 'tipo': 'R D ATIVA - COFINS - LANÇADO DE OFÍCIO - SIMPLES NACIONAL'},
     {'codigo': 3163, 'tipo': 'R D ATIVA - PIS - LANÇADO DE OFÍCIO - SIMPLES NACIONAL'},
     {'codigo': 3192, 'tipo': 'R D ATIVA - CONTRIB PREVID PATRONAL -LANÇADO OFÍCIO - SIMPLES NAC'},
     {'codigo': 3219, 'tipo': 'IRPJ - GANHO CAPITAL -ALIENAÇÃO ATIVO - SIMPLES NACIONAL - LANÇ OF'},
     {'codigo': 3231, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - REMESSA POSTAL'},
     {'codigo': 3290, 'tipo': 'R D ATIVA - MULTA DESTINADA AO FUNDO DE AMPARO AO TRABALHADOR- FAT'},
     {'codigo': 3339, 'tipo': 'R D ATIVA - PAGAMENTO UNIFICADO - INCORPORAÇÕES - PMCMV'},
     {'codigo': 394, 'tipo': 'CONTRIBUIÇÃO PRÊMIOS PRESCRITOS - LEI 5.768/1971'},
     {'codigo': 3407, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - IE - NÃO TRIBUTÁRIO'},
     {'codigo': 3442, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - CSLL - NÃO TRIBUTÁRIO'},
     {'codigo': 3459, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - CIDE - NÃO TRIBUTÁRIO'},
     {'codigo': 3504, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - CONTRIB PREVID -NÃO TRIBUTÁRIO'},
     {'codigo': 3864, 'tipo': 'MULTA POR ATRASO/ERRO/OMISSÃO - SISCOSERV'},
     {'codigo': 4720, 'tipo': 'LEI 12.996, DE 2014 - PGFN - DÉBITOS PREVIDENCIÁRIOS -PARCELAMENTO'},
     {'codigo': 4737, 'tipo': 'LEI Nº 12.996, DE 2014 - PGFN - DEMAIS DÉBITOS - PARCELAMENTO'},
     {'codigo': 4743, 'tipo': 'LEI 12.996, DE 2014 - RFB - DÉBITOS PREVIDENCIÁRIOS - PARCELAMENTO'},
     {'codigo': 4772, 'tipo': 'LEI 12.996/14 -PGFN -DEMAIS DÉBITOS -PGTO PF/BASE CÁLC NEG DA CSLL'},
     {'codigo': 4805, 'tipo': 'TAXA PELA UTILIZAÇÃO SELO CONTROLE - LEI 12995/14 - ART 13 - INC I'},
     {'codigo': 4811, 'tipo': 'TAXA UTILIZAÇÃO CONTADORES DE PRODUÇÃO -L12995/14 -ART 13 - INC II'},
     {'codigo': 4840, 'tipo': 'MULTA - PARCELA NÃO RESTITUÍDA - INFRAÇÃO À LEGISL- DOLO/MÁ-FÉ -PF'},
     {'codigo': 4892, 'tipo': 'L 12996/14 - PGFN -DÉB PREVIDENCIÁRIO -PARCELAMENTO - DEP JUDICIAL'},
     {'codigo': 4902, 'tipo': 'LEI 12996/14 - PGFN - DEMAIS DÉBITOS - PARCELAMENTO - DEP JUDICIAL'},
     {'codigo': 4919, 'tipo': 'L 12.996/14 - RFB - DÉBITO PREVIDENCIÁRIO - PARCELAMENTO - DEP JUD'},
     {'codigo': 4931, 'tipo': 'LEI 12.996/14 - RFB - DEMAIS DÉBITOS - PARCELAMENTO - DEP JUDICIAL'},
     {'codigo': 4857, 'tipo': 'CONT PREV S/ REC ASSOC DESP FUT PROF-SUBST À CONT PATR-LANÇ OFÍCIO'},
     {'codigo': 4863, 'tipo': 'CONTRIBUIÇÃO PREV S/ COMERCIALIZAÇÃO PRODUÇÃO RURAL - LANÇ. OFÍCIO'},
     {'codigo': 3709, 'tipo': 'AFRMM - LEI Nº 10.893/2004 - ART. 17 (I A OU I B)'},
     {'codigo': 3773, 'tipo': 'TUM - TAXA DE UTILIZAÇÃO DO MERCANTE'},
     {'codigo': 5006, 'tipo': 'TUM - TAXA DE UTILIZAÇÃO DO MERCANTE - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 5029, 'tipo': 'IRRF - GANHO CAPITAL - INTEGRAL COTA C/ ATIVO -L 13043/2014(ART 1)'},
     {'codigo': 5035, 'tipo': 'IRRF - EMPRÉSTIMO DE ATIVO -FUNDO INVESTIMENTO -L 13043/14 (ART 8)'},
     {'codigo': 5064, 'tipo': 'PARCELAMENTO PROFUT - DEMAIS DÉBITOS - RFB'},
     {'codigo': 5155, 'tipo': 'DEPÓSITOS JUDICIAIS - ROYALTIES E/OU PARTICIPAÇÃO ESPECIAL - DJE'},
     {'codigo': 8811, 'tipo': 'REFIS - DEPÓSITO JUDICIAL'},
     {'codigo': 8944, 'tipo': 'II - IMPOSTO IMPORTAÇÃO - GARANTIA ADUANEIRA/DEP ADMINISTRATIVO'},
     {'codigo': 4750, 'tipo': 'LEI Nº 12.996, DE 2014 - RFB - DEMAIS DÉBITOS - PARCELAMENTO'},
     {'codigo': 4766, 'tipo': 'LEI 12996/14 -PGFN -DÉBITOS PREV -PGTO PF/BASE DE CÁLC NEG DA CSLL'},
     {'codigo': 4983, 'tipo': 'PARCELAMENTO - IRPJ/CSLL - GANHO DE CAPITAL - RFB'},
     {'codigo': 5087, 'tipo': 'PARCELAMENTO PROFUT - DEMAIS DÉBITOS - PGFN'},
     {'codigo': 5058, 'tipo': 'REG TRIB SIMPL - MERC IMP Ñ IDENT - ART 67 L 10833/03- LANÇ OFÍCIO'},
     {'codigo': 8957, 'tipo': 'IPI - VINCULADO À IMPORTAÇÃO - GARANTIA ADUAN - DEP ADMINISTRATIVO'},
     {'codigo': 5246, 'tipo': 'ROYALTIES 5% (E/M) L 7990 ART 7 I A III - DJE'},
     {'codigo': 5252, 'tipo': 'ROYALTIES ATÉ 5% - LAVRA NA ÁREA PRÉ-SAL - EM PLATAFORMA - DJE'},
     {'codigo': 5269, 'tipo': 'ROYALTIES 5% (E-M) (L 7990 ART. 7 P 4) - DJE'},
     {'codigo': 5281, 'tipo': 'ROYALTIES ATÉ 5% - ART. 2º DA LEI Nº 12.858/2013 - DJE'},
     {'codigo': 5298, 'tipo': 'ROYALTIES EXCEDENTES A 5% (E/M) LEI Nº 9.478/97, ART. 49, I - DJE'},
     {'codigo': 5308, 'tipo': 'ROYALTIES EXCEDENTES A 5% (MCT) LEI Nº 9.478/97, ART. 49, I - DJE'},
     {'codigo': 5337, 'tipo': 'ROYALTIES EXCEDENTES A 5% (E-M) - LEI Nº 9478/97, ART 49, II - DJE'},
     {'codigo': 5366, 'tipo': 'PARTICIPAÇÃO ESPECIAL (E-M) - LEI Nº 9.478/1997, ART. 50 - DJE'},
     {'codigo': 7372, 'tipo': 'PARTICIPAÇÃO ESPECIAL (MME/MMA) - LEI Nº 9.478/1997, ART. 50 - DJE'},
     {'codigo': 5372, 'tipo': 'PARTICIPAÇÃO ESPECIAL (MME/MMA) - LEI Nº 9.478/1997, ART. 50 - DJE'},
     {'codigo': 5405, 'tipo': 'PARTICIPAÇÃO ESPECIAL - ART. 2º DA LEI Nº 12.858/2013 - DJE'},
     {'codigo': 5411, 'tipo': 'ROYALTY - PARTILHA -15%- ART 42 L 12351/10 - PRÉ-SAL/ÁREA ESTRATÉG'},
     {'codigo': 5428, 'tipo': 'ROYALTY- PARTILHA-15%- ART 42 L 12351/10 -PRÉ-SAL/ÁREA ESTRAT- DJE'},
     {'codigo': 5440, 'tipo': 'MULTA POR ATRASO NA ENTREGA DA DCTFWEB'},
     {'codigo': 5492, 'tipo': 'CPSS/FCDF - SERVIDOR CIVIL ATIVO'}, {'codigo': 5519, 'tipo': 'CPSS/FCDF - PATRONAL'},
     {'codigo': 5470, 'tipo': 'PERDIMENTO DE BENS APREENDIDOS - DJE'},
     {'codigo': 5184, 'tipo': 'PROGRAMA DE REGULARIZAÇÃO TRIBUTÁRIA (PRT) - DEMAIS DÉBITOS'},
     {'codigo': 5200, 'tipo': 'IRRF - REND TRABALHO - HONORÁRIOS ADVOC SUCUMBÊNCIA - LEI 13327/16'},
     {'codigo': 5132, 'tipo': 'MULTA P/ FALTA/ATRASO - PREST INFORMAÇÃO S/ VEÍCULO/CARGA/OPERAÇÃO'},
     {'codigo': 4789, 'tipo': 'LEI 12.996/14 - RFB - DÉBITOS PREV - PGTO PF/BASE CÁLC NEG DA CSLL'},
     {'codigo': 4990, 'tipo': 'PARCELAMENTO - IRPJ/CSLL - GANHO DE CAPITAL - PGFN'},
     {'codigo': 5275, 'tipo': 'COTA PARTE INDENIZAÇÃO PELA EXTRAÇÃO PETRÓLEO/XISTO/GÁS (MM) - DJE'},
     {'codigo': 5502, 'tipo': 'CPSS/FCDF - SERVIDOR CIVIL INATIVO/PENSIONISTA'},
     {'codigo': 5103, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - CPSS - NÃO TRIBUTÁRIO'},
     {'codigo': 5525, 'tipo': 'PROGRAMA REGULARIZAÇÃO DÉB PREV ESTADO/MUNICÍPIO (PREM)- MP 778/17'},
     {'codigo': 5190, 'tipo': 'PROGRAMA ESPECIAL REGULARIZAÇÃO TRIBUTÁRIA (PERT) - DEMAIS DÉBITOS'},
     {'codigo': 5161, 'tipo': 'PROGRAMA DE REGULARIZAÇÃO TRIBUTÁRIA RURAL (PRR)'},
     {'codigo': 1872, 'tipo': 'SEGURADO EMPREGADO - RECOLHIMENTO MENSAL - COMPLEMENTO'},
     {'codigo': 3961, 'tipo': 'ROYALTIES ATÉ 5% - ART. 2º DA LEI Nº 12.858/2013'},
     {'codigo': 3978, 'tipo': 'ROYALTIES EXCEDENTE A 5% - ART. 2º DA LEI Nº 12.858/2013'},
     {'codigo': 4795, 'tipo': 'LEI 12.996/14 -RFB -DEMAIS DÉBITOS - PGTO PF/BASE CÁLC NEG DA CSLL'},
     {'codigo': 3767, 'tipo': 'AFRMM - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 4834, 'tipo': 'R D ATIVA - MULTA POR ATRASO NA ENTREGA DE DECLARAÇÃO - MAED'},
     {'codigo': 5457, 'tipo': 'ALIENAÇÃO DE BENS APREENDIDOS - SISTEMA DE LEILÃO ELETRÔNICO'},
     {'codigo': 5314, 'tipo': 'ROYALTY EXCEDENTE A 5% - LAVRA ÁREA PRÉ-SAL - EM PLATAFORMA - DJE'},
     {'codigo': 5343, 'tipo': 'ROYALTIES EXCEDENTES A 5% (MM/MCT) - LEI 9478/97, ART 49, II - DJE'},
     {'codigo': 5350, 'tipo': 'ROYALTIES EXCEDENTE A 5% - ART. 2º DA LEI Nº 12.858/2013 - DJE'},
     {'codigo': 3990, 'tipo': 'PARTICIPAÇÃO ESPECIAL - ART. 2º DA LEI Nº 12.858/2013'},
     {'codigo': 3770, 'tipo': 'PIS - RET FONTE - AQUISIÇÃO DE AUTOPEÇAS'},
     {'codigo': 2687, 'tipo': 'R D ATIVA - MULTA PREVISTA LEG DEF DIR DIFUSO'},
     {'codigo': 883, 'tipo': 'R D ATIVA – JUROS ISOLADOS - CSIRF(ART. 43 - LEI Nº 9.430 DE 1996)'},
     {'codigo': 1772, 'tipo': 'R D ATIVA - RETENÇÃO FONTE CONTRIBUIÇÕES PAGT PJ A PJ DIR PRIVADO'},
     {'codigo': 1731, 'tipo': 'R D ATIVA - RETENÇÃO FONTE CONTRIB PAGT EST/DF/MUNIC – BENS E SERV'},
     {'codigo': 1729, 'tipo': 'R D ATIVA – RETENÇÃO EM PAGAMENTO POR ÓRGÃO PÚBLICO'},
     {'codigo': 1703, 'tipo': 'R D ATIVA – SERVIÇOS - RETENÇÃO EM PAGAMENTO POR ÓRGÃO PÚBLICO'},
     {'codigo': 1691, 'tipo': 'R D ATIVA – FINANCEIRAS – RETENÇÃO EM PAGAMENTO POR ÓRGÃO PÚBLICO'},
     {'codigo': 1689, 'tipo': 'R D ATIVA – BENS/SERV ADQUIR COOPER/ASSOC PROFISS - RET ÓRGÃO PUBL'},
     {'codigo': 1595, 'tipo': 'R D ATIVA – TRANSPORTE INTERNACIONAL PASSAGEIRO - RET ÓRGÃO PUBL'},
     {'codigo': 1582, 'tipo': 'R D ATIVA – TRANSPORTE DE PASSAGEIRO – RETENÇÃO POR ÓRGÃO PÚBLICO'},
     {'codigo': 1570, 'tipo': 'R D ATIVA - MEDICAMENTO ADQUIR INDUST/IMPORT - RETIDO ÓRGÃO PUBL'},
     {'codigo': 761, 'tipo': 'R D ATIVA - REGIME ESPECIAL DE TRIBUTAÇÃO DO PATRIMÔNIO AFETAÇÃO'},
     {'codigo': 855, 'tipo': 'COFINS - IMPORTAÇÃO - DEPÓSITO ADMINISTRATIVO'},
     {'codigo': 1947, 'tipo': 'PIS - IMPORTAÇÃO - DEPÓSITO JUDICIAL'},
     {'codigo': 1994, 'tipo': 'COFINS - IMPORTAÇÃO - DEPÓSITO JUDICIAL'},
     {'codigo': 434, 'tipo': 'COFINS - IMPORTAÇÃO DE SERVIÇOS- LANÇAMENTO DE OFÍCIO'},
     {'codigo': 449, 'tipo': 'PIS-IMPORTAÇÃO DE SERVIÇOS-LANÇAMENTO DE OFÍCIO'},
     {'codigo': 5590, 'tipo': 'FUNDAF-VISTOR TEC E AUD SIST INF-ALFAND-HAB DESP ADUAN'},
     {'codigo': 340, 'tipo': 'JUROS ISOLADOS REC DIREITOS ANTIDUMP E COMPENS ART. 7º LEI 9019/95'},
     {'codigo': 298, 'tipo': 'IMPOSTO DE EXPORTAÇÃO-LANÇAMENTO DE OFÍCIO'},
     {'codigo': 285, 'tipo': 'PARCELAMENTO PARA INGRESSO NO SIMPLES NACIONAL'},
     {'codigo': 191, 'tipo': 'CSLL - TRIBUTAÇÃO DIFERIDA/OPÇÃO PELO SIMPLES - LANÇ OFÍCIO'},
     {'codigo': 338, 'tipo': 'MULTA ISOLADA REC DIREITOS ANTIDUMP E COMPENS ART. 7º LEI 9019/95'},
     {'codigo': 2991, 'tipo': 'CONTRIB PREVID SOBRE RECEITA BRUTA - ART. 8º LEI 12.546/2011'},
     {'codigo': 3248, 'tipo': 'MULTA ADUANEIRA - REMESSA POSTAL'},
     {'codigo': 3368, 'tipo': 'R D ATIVA - PAGAMENTO UNIFICADO - CONSTRUÇÕES - PMCMV'},
     {'codigo': 3413, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - IPI - NÃO TRIBUTÁRIO'},
     {'codigo': 3465, 'tipo': 'DEVOLUÇÃO DE RESTITUIÇÃO INDEVIDA - PIS/PASEP - NÃO TRIBUTÁRIO'},
     {'codigo': 3540, 'tipo': 'IRRF -BENEFÍCIO PREV COMPLEMENTAR/NÃO OPTANTE TRIBUTAÇÃO EXCLUSIVA'},
     {'codigo': 3676, 'tipo': 'MULTA ATRASO ENVIO ALVARÁ E/OU HABITE-SE'},
     {'codigo': 3796, 'tipo': 'REABERTURA LEI 11.941/09 - PGFN - DÉBITOS PREVIDENCIÁRIOS - ART. 3'},
     {'codigo': 3835, 'tipo': 'REABERTURA L 11941/09-PGFN-DEMAIS DÉB- PARC DÍV NÃO PARC ANT-ART 1'},
     {'codigo': 3932, 'tipo': 'REABERTURA LEI Nº 11.941, DE 2009 - RFB - DEMAIS DÉBITOS - ART 3'},
     {'codigo': 4042, 'tipo': 'LEI Nº 12.865/2013 - PGFN - PARCELAMENTO PIS/COFINS - ART 39, § 1º'},
     {'codigo': 4059, 'tipo': 'LEI Nº 12.865, DE 2013 - RFB - PARCELAMENTO IRPJ/CSLL - ART. 40'},
     {'codigo': 4065, 'tipo': 'LEI Nº 12.865, DE 2013 - PGFN - PARCELAMENTO IRPJ/CSLL - ART. 40'},
     {'codigo': 4088, 'tipo': 'LEI 12865/13 - PGFN -PAGAMENTO À VISTA - PIS/COFINS -ART 39, CAPUT'},
     {'codigo': 4094, 'tipo': 'LEI 12865/2013 - RFB - PAGAMENTO À VISTA PIS/COFINS - ART 39, § 1º'},
     {'codigo': 4104, 'tipo': 'LEI 12865/2013 - PGFN -PAGAMENTO À VISTA -PIS/COFINS -ART 39, § 1º'},
     {'codigo': 4110, 'tipo': 'LEI 12.865, DE 2013 - RFB - PAGAMENTO À VISTA - IRPJ/CSLL - ART 40'},
     {'codigo': 4127, 'tipo': 'LEI 12865, DE 2013 - PGFN - PAGAMENTO À VISTA - IRPJ/CSLL - ART 40'},
     {'codigo': 244, 'tipo': 'IOF - OURO ATIVO FINANCEIRO - LANÇAMENTO DE OFÍCIO'},
     {'codigo': 4584, 'tipo': 'ENCARGOS POR REPASSE FORA DO PRAZO - IFC - SIMPLES NACIONAL'},
     {'codigo': 216, 'tipo': 'DEPÓSITO JUDICIAL - OUTROS - ADUANEIROS'},
     {'codigo': 229, 'tipo': 'DEPÓSITO ADMINISTRATIVO - OUTROS - ADUANEIROS'},
     {'codigo': 135, 'tipo': 'CONTRIBUIÇÃO LOTERIA ESPECIAL - TIMEMANIA'},
     {'codigo': 468, 'tipo': 'COFINS-REGIME ESPECIAL TRIBUTAÇÃO-PATRIMÔNIO AFETAÇÃO-LANÇ OFÍCIO'},
     {'codigo': 507, 'tipo': 'IRPJ-GANHO CAP-ALIENAÇÃO ATIVOS ME/EPP OPTANTES SIMPLES NACIONAL'},
     {'codigo': 513, 'tipo': 'PIS-REGIME ESPECIAL TRIBUTAÇÃO-PATRIMÔNIO AFETAÇÃO-LANÇ DE OFÍCIO'},
     {'codigo': 830, 'tipo': 'PARCELAMENTO ART. 1º MP 303/2006 - PJ OPTANTE PELO SIMPLES'},
     {'codigo': 497, 'tipo': 'PIS - IMPORTAÇÃO - NÃO PAGO DEVIDO SUSPENSÃO'},
     {'codigo': 565, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DBF'},
     {'codigo': 439, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DTTA'},
     {'codigo': 656, 'tipo': 'MULTA POR FALTA OU ATRASO NA ENTREGA DA DECRED'},
     {'codigo': 685, 'tipo': 'R D ATIVA - MULTA REGIME DISCIPLINAR DA RARF'},
     {'codigo': 880, 'tipo': 'DEVOLUÇÃO DE RETITUIÇÃO INDEVIDA - COFINS/FINSOCIAL - NÃO TRIBUTÁR'},
     {'codigo': 679, 'tipo': 'PIS - TRIBUTAÇÃO DE BEBIDAS FRIAS - CERVEJAS'},
     {'codigo': 809, 'tipo': 'COFINS IMPORTAÇÃO -TRIBUTAÇÃO DE BEBIDAS FRIAS - DEMAIS BEBIDAS'},
     {'codigo': 821, 'tipo': 'IPI - TRIBUTAÇÃO DE BEBIDAS FRIAS - CERVEJAS'},
     {'codigo': 838, 'tipo': 'IPI - TRIBUTAÇÃO DE BEBIDAS FRIAS - DEMAIS BEBIDAS'},
     {'codigo': 850, 'tipo': 'IPI VINCULADO A IMPORTAÇÃO-TRIBUTAÇÃO DE BEBIDAS FRIAS - CERVEJAS'},
     {'codigo': 912, 'tipo': 'PIS-IMPORTAÇÃO-REGIME ESPECIAL DE APURAÇÃO E PAGAMENTO - ÁLCOOL'},
     {'codigo': 929, 'tipo': 'COFINS - REGIME ESPECIAL DE APURAÇÃO E PAGAMENTO - ÁLCOOL'},
     {'codigo': 1039, 'tipo': 'R D ATIVA - RECUPERAÇÃO DE RECURSOS - FINOR'},
     {'codigo': 1045, 'tipo': 'R D ATIVA - RECUPERAÇÃO DE RECURSOS - FINAM'},
     {'codigo': 1165, 'tipo': 'LEI 11.941/09-PGFN-DEB PREV-PARCELAMENTO ART. 3º'},
     {'codigo': 1188, 'tipo': 'LEI 11.941/09-PGFN-DEMAIS DEB-PG C/ PREJ FISCAL BC NEG CSLL'}]

    value_to_return = ''
    for i in range(len(tributos)):
        if valor == str(tributos[i].get('codigo')):
            value_to_return = tributos[i].get('tipo')

    return value_to_return
